<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="Chapter 9 N Parameters | Gov 50: Data" />
<meta property="og:type" content="book" />



<meta name="github-repo" content="davidkane9/PPBDS" />



<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="Chapter 9 N Parameters | Gov 50: Data">

<title>Chapter 9 N Parameters | Gov 50: Data</title>

<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/envisioned.css" rel="stylesheet" />
<link href="libs/msmb-css-0/msmb.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);

e.style.display = ((e.style.display!='none') ? 'none' : 'block');

if(f.classList.contains('fa-plus-square')) {
    f.classList.add('fa-minus-square')
    f.classList.remove('fa-plus-square')
} else {
    f.classList.add('fa-plus-square')
    f.classList.remove('fa-minus-square')
}

}
</script>
<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<link href="libs/str_view-0.1.0/str_view.css" rel="stylesheet" />
<script src="libs/str_view-binding-1.4.0/str_view.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }

code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul class="navbar">
<li class="msmb"><p class="title">Gov 50: Data<p><p class="author"></p>
<li class="dropdown" style="float:right">
<a href="javascript:void(0)" class="dropbtn">&#x25BE; Chapters</a>
<div class="dropdown-content">
<a href="index.html"></a>
<a href="preamble.html">Preamble</a>
<a href="shopping-week.html">Shopping Week</a>
<a href="visualization.html"><span class="toc-section-number">1</span> Visualization</a>
<a href="wrangling.html"><span class="toc-section-number">2</span> Wrangling</a>
<a href="rubin-causal-model.html"><span class="toc-section-number">3</span> Rubin Causal Model</a>
<a href="functions.html"><span class="toc-section-number">4</span> Functions</a>
<a href="probability.html"><span class="toc-section-number">5</span> Probability</a>
<a href="one-parameter.html"><span class="toc-section-number">6</span> One Parameter</a>
<a href="two-parameters.html"><span class="toc-section-number">7</span> Two Parameters</a>
<a href="three-parameters.html"><span class="toc-section-number">8</span> Three Parameters</a>
<a id="active-page" href="n-parameters.html"><span class="toc-section-number">9</span> N Parameters</a><ul class="toc-sections">
<li class="toc"><a href="#eda-of-governors"> EDA of <code>governors</code></a></li>
<li class="toc"><a href="#wisdom"> Wisdom</a></li>
<li class="toc"><a href="#justice-and-courage"> Justice and Courage</a></li>
<li class="toc"><a href="#temperance"> Temperance</a></li>
<li class="toc"><a href="#eda-of-shaming"> EDA of <code>shaming</code></a></li>
<li class="toc"><a href="#causal-effects-of-treament"> Causal Effects of <code>treament</code></a></li>
</ul>
<a href="model-choice.html"><span class="toc-section-number">10</span> Model Choice</a>
<a href="continuous-response.html"><span class="toc-section-number">11</span> Continuous Response</a>
<a href="discrete-response.html"><span class="toc-section-number">12</span> Discrete Response</a>
<a href="appendices.html">Appendices</a>
<a href="tools.html">Tools</a>
<a href="shiny.html">Shiny</a>
<a href="maps.html">Maps</a>
<a href="animation.html">Animation</a>
<a href="references.html">References</a>
</div>
</li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><div id="n-parameters" class="section level1">
<h1>
<span class="header-section-number">Chapter 9</span> N Parameters</h1>
<p><em>This chapter is a draft.</em> Come back in a few weeks for a better version.</p>
<p>Having created models with one parameter in Chapter <a href="one-parameter.html#one-parameter">6</a>, two parameters in Chapter <a href="two-parameters.html#two-parameters">7</a> and three parameters in Chapter <a href="three-parameters.html#three-parameters">8</a>, you are now ready to make the jump to <span class="math inline">\(N\)</span> parameters.</p>
<p>In this chapter, we will consider models with multiple parameters and the complexities that arise therefrom.</p>
<!-- DK: Add some more. What are the key lessons? What do we carry over from previous chapters? What is new? -->
<div id="eda-of-governors" class="section level2">
<h2>
<span class="header-section-number">9.1</span> EDA of <code>governors</code>
</h2>
<p>Load packages:</p>
<div class="sourceCode" id="cb928"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb928-1"><a href="n-parameters.html#cb928-1"></a><span class="kw">library</span>(PPBDS.data)</span>
<span id="cb928-2"><a href="n-parameters.html#cb928-2"></a><span class="kw">library</span>(skimr)</span>
<span id="cb928-3"><a href="n-parameters.html#cb928-3"></a><span class="kw">library</span>(rstanarm)</span>
<span id="cb928-4"><a href="n-parameters.html#cb928-4"></a><span class="kw">library</span>(tidyverse)</span></code></pre></div>
<!-- DK: Was all this covered? --- Talk about the data, as we usual do. Lots of interesting things. Explain how we only have data for people who are already dead. That is an interesting restriction, and effects the Preceptor Table in interesting ways. Make sure to mention all the variables we end up keeping below. Finish with some graphics which show how various things are related to our lefthand side variable: alive_post. -->
<p>We will start off by using a subset of the <code>governors</code> data set from the <strong>PPBDS.data</strong> package. This data set looks at the lifespans of candidates for governor in the US. It comes from the paper “Longevity Returns to Political Office” by Barfort, Klemmensen &amp; Larsen (2019), which concludes that winning a gubernatorial election increases a candidate’s lifespan.</p>
<div class="sourceCode" id="cb929"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb929-1"><a href="n-parameters.html#cb929-1"></a><span class="kw">glimpse</span>(governors)</span></code></pre></div>
<pre><code>## Rows: 1,092
## Columns: 11
## $ state      &lt;chr&gt; "Alabama", "Alabama", "Alabama", "Alabama", "Alabama", "Al…
## $ year       &lt;int&gt; 1946, 1946, 1950, 1954, 1954, 1958, 1962, 1966, 1966, 1970…
## $ first_name &lt;chr&gt; "James", "Lyman", "Gordon", "Tom", "James", "William", "Ge…
## $ last_name  &lt;chr&gt; "Folsom", "Ward", "Persons", "Abernethy", "Folsom", "Longs…
## $ party      &lt;chr&gt; "Democrat", "Republican", "Democrat", "Republican", "Democ…
## $ sex        &lt;chr&gt; "Male", "Male", "Male", "Male", "Male", "Male", "Male", "M…
## $ died       &lt;date&gt; 1987-11-21, 1948-12-17, 1965-05-29, 1968-03-07, 1987-11-2…
## $ status     &lt;chr&gt; "Challenger", "Challenger", "Challenger", "Challenger", "C…
## $ win_margin &lt;dbl&gt; 77.3, -77.3, 82.2, -46.7, 46.7, -77.5, 100.0, -34.3, 34.3,…
## $ alive_post &lt;int&gt; 14991, 773, 5319, 4871, 12069, 19924, 13096, 18622, 549, 1…
## $ alive_pre  &lt;int&gt; 13906, 28690, 17805, 17001, 16828, 12152, 15778, 17597, 14…</code></pre>
<p>There are 11 variables and 1,092 observations. In this Chapter, we will only be looking at the variables <code>last_name</code>, <code>year</code>, <code>state</code>, <code>sex</code>, <code>status</code>, <code>alive_post</code>, and <code>alive_pre</code>. We will also create a new variable called <code>won</code> that is <code>TRUE</code> if the candidate won the election, and <code>FALSE</code> if not.</p>
<div class="sourceCode" id="cb931"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb931-1"><a href="n-parameters.html#cb931-1"></a>ch9_gov &lt;-<span class="st"> </span>governors <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb931-2"><a href="n-parameters.html#cb931-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">won =</span> <span class="kw">ifelse</span>(win_margin <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>, <span class="ot">TRUE</span>, <span class="ot">FALSE</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb931-3"><a href="n-parameters.html#cb931-3"></a><span class="st">  </span><span class="kw">select</span>(last_name, year, state, sex, status, won, alive_post, alive_pre)</span></code></pre></div>
<p>There are a few things to note when looking at this data. First, the data set includes the variables <code>alive_pre</code> and <code>alive_post</code>, which tell us how many days a candidate lived before the election took place and how many days a candidate lived after the election, respectively. Therefore, only politicians who are already deceased are included in this data set. This means that there are only a handful of observations from elections in the last 20 years. Most candidates from that time are still alive and are excluded.</p>
<p>Another caveat is that for a given election, only the top two candidates are included in the data. If a politician did not receive the highest or second-highest number of votes, they are excluded.</p>
<p>Finally, for some observations, only the birth or death year of a candidate could be determined and not the exact date. In those cases, the date was set as July 1st of that year.</p>
<p>Let’s run <code>sample_n()</code>:</p>
<div class="sourceCode" id="cb932"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb932-1"><a href="n-parameters.html#cb932-1"></a><span class="kw">sample_n</span>(ch9_gov, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>## # A tibble: 10 x 8
##    last_name  year state         sex   status     won   alive_post alive_pre
##    &lt;chr&gt;     &lt;int&gt; &lt;chr&gt;         &lt;chr&gt; &lt;chr&gt;      &lt;lgl&gt;      &lt;int&gt;     &lt;int&gt;
##  1 Meyner     1969 New Jersey    Male  Challenger FALSE       7508     22405
##  2 Beall      1978 Maryland      Male  Challenger FALSE      10001     18767
##  3 Forbes     1957 New Jersey    Male  Challenger FALSE      11799     13958
##  4 Blaylock   1972 Arkansas      Male  Challenger FALSE      14385     19691
##  5 Ostlund    1978 Wyoming       Male  Challenger FALSE       9305     18665
##  6 Pastore    1948 Rhode Island  Male  Incumbent  TRUE       18880     15209
##  7 Conrad     1976 Indiana       Male  Challenger FALSE       4992     15246
##  8 Rice       1946 Pennsylvania  Male  Challenger FALSE      14150     17447
##  9 Arn        1950 Kansas        Male  Challenger TRUE       17245     16241
## 10 Powell     1958 New Hampshire Male  Challenger TRUE        8098     15729</code></pre>
<p>From this sample, we can see some trends start to appear. For example, we see that <code>sex</code> is most often “Male”, and status is most often “Challenger” rather than “Incumbent”.</p>
<div class="sourceCode" id="cb934"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb934-1"><a href="n-parameters.html#cb934-1"></a><span class="kw">skim</span>(ch9_gov)</span></code></pre></div>
<p><!--
<caption>--><span class="marginnote shownote"><span id="tab:unnamed-chunk-732">TABLE 9.1: </span>Data summary</span><!--</caption>--></p>
<table><tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">ch9_gov</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">1092</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">8</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">4</td>
</tr>
<tr class="odd">
<td align="left">logical</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">3</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody></table>
<p><strong>Variable type: character</strong></p>
<table>
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">last_name</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">11</td>
<td align="right">0</td>
<td align="right">615</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">state</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">14</td>
<td align="right">0</td>
<td align="right">50</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">sex</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">status</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">9</td>
<td align="right">10</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: logical</strong></p>
<table>
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="left">count</th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">won</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0.53</td>
<td align="left">TRU: 576, FAL: 516</td>
</tr></tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">year</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1965</td>
<td align="right">13</td>
<td align="right">1945</td>
<td align="right">1954</td>
<td align="right">1962</td>
<td align="right">1974</td>
<td align="right">2011</td>
<td align="left">▇▆▃▂▁</td>
</tr>
<tr class="even">
<td align="left">alive_post</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">10310</td>
<td align="right">4886</td>
<td align="right">46</td>
<td align="right">6419</td>
<td align="right">10811</td>
<td align="right">14124</td>
<td align="right">22067</td>
<td align="left">▃▆▇▆▂</td>
</tr>
<tr class="odd">
<td align="left">alive_pre</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">18892</td>
<td align="right">3181</td>
<td align="right">11450</td>
<td align="right">16561</td>
<td align="right">18758</td>
<td align="right">20996</td>
<td align="right">30633</td>
<td align="left">▂▇▆▂▁</td>
</tr>
</tbody>
</table>
<p>This output groups the variables together by type (character, logical, numeric, etc.). From this, we can see things like the number of unique last names, how many of the observations in our subset won versus how many lost their elections, and the mean number of days before and after a gubernatorial election that a candidate lived. We are also given histograms of the numerical data. In looking at the histogram for <code>year</code>, we see that it is skewed right, with half of the observations from election years between 1945 and 1962. This makes sense logically, because we are only looking at deceased candidates, and candidates from more recent elections are more likely to still be alive.</p>
<!-- DK: Would using years rather than days as the unit be helpful? -->
<p>In using this data set, our left-side variable will be <code>alive_post</code>. We are trying to understand/predict how many days a candidate will live after the election. Let’s look at some graphs and plots showing the relationships between <code>alive_post</code> and some of the other variables in our subset.</p>
<!-- DK: Clean up the plot. -->
<div class="sourceCode" id="cb935"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb935-1"><a href="n-parameters.html#cb935-1"></a>ch9_gov <span class="op">%&gt;%</span></span>
<span id="cb935-2"><a href="n-parameters.html#cb935-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> alive_post)) <span class="op">+</span></span>
<span id="cb935-3"><a href="n-parameters.html#cb935-3"></a><span class="st">  </span><span class="kw">geom_point</span>()</span></code></pre></div>
<p><img src="book_temp_files/figure-html/unnamed-chunk-733-1.png" width="672"></p>
<p>Starting with the relationship between <code>alive_post</code> and <code>year</code>, we can see that the data is skewed right and that there is a defined line that data points do not exist above. There are no data points in the top right portion of the graph because it is not possible to have run in 2011, lived 20,000 days after the election took place, and still have died before the data set was created. This line represents, approximately, the most a candidate could have possibly lived — and still have died — to be included the data set. The reason this line is slanted downward is because the maximum value for this scenario is greater in earlier years. That is, those candidates who ran for governor in earlier years could live a longer time after the election and still have died prior to the data set creation, giving them higher <code>alive_post</code> values than those who ran for office in more recent years.</p>
<p>There are fewer observations in later years because fewer candidates have died. The vast majority of candidates who ran for office in the 21st century are still alive today and therefore excluded.</p>
<!-- DK: Clean up plot. -->
<div class="sourceCode" id="cb936"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb936-1"><a href="n-parameters.html#cb936-1"></a>ch9_gov <span class="op">%&gt;%</span></span>
<span id="cb936-2"><a href="n-parameters.html#cb936-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> sex, <span class="dt">y =</span> alive_post)) <span class="op">+</span></span>
<span id="cb936-3"><a href="n-parameters.html#cb936-3"></a><span class="st">  </span><span class="kw">geom_boxplot</span>()</span></code></pre></div>
<p><img src="book_temp_files/figure-html/unnamed-chunk-734-1.png" width="672"></p>
<p>This plot shows that men live much longer, on average, than women after the election. Does that make sense to you?</p>
<!-- Clean up and add more discussion here -->
</div>
<div id="wisdom" class="section level2">
<h2>
<span class="header-section-number">9.2</span> Wisdom</h2>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:unnamed-chunk-735"></span>
<img src="other/images/Wisdom.jpg" alt="Wisdom" width="1280"><!--
<p class="caption marginnote">-->FIGURE 9.1: Wisdom<!--</p>-->
<!--</div>--></span>
</p>
<!-- DK: Two paragraphs is plenty. Note this is a change. Topic is: If we want to predict how long someone will live, how relevant is this data set? (We are not interested in the question which the authors explore which is the causal effect of victory on lifespan.) We are making a predictive model, not a causal one. Can we use this model for any new person we meet? Only for people who are candidates? For people who are about as rich/successful/educated as the typical candidate? -->
</div>
<div id="justice-and-courage" class="section level2">
<h2>
<span class="header-section-number">9.3</span> Justice and Courage</h2>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:unnamed-chunk-736"></span>
<img src="other/images/Justice.jpg" alt="Justice" width="960"><!--
<p class="caption marginnote">-->FIGURE 9.2: Justice<!--</p>-->
<!--</div>--></span>
</p>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:unnamed-chunk-737"></span>
<img src="other/images/Courage.jpg" alt="Courage" width="1024"><!--
<p class="caption marginnote">-->FIGURE 9.3: Courage<!--</p>-->
<!--</div>--></span>
</p>
<p>Because we will be going through a series of models in this chapter, it is useful to combine the virtues of Justice and Courage.</p>
<p>Let’s explore descriptive, not causal, models which seek to predict longevity post-election.</p>
<p>To begin, let’s model candidate lifespan after the election as a function of candidate lifespan prior to the election. The math is fairly simple:</p>
<p><span class="math display">\[ alive\_post_i =  \beta_0 + \beta_1 alive\_pre_i + \epsilon_i \]</span></p>
<!-- DK: I need to think harder about exactly what these cofficients mean in the Bayesian context. We can't just rely on the "average value for the population" verbiage which we used in chapters 7 and 8. -->
<p>with <span class="math inline">\(\epsilon_i \sim N(0, \sigma^2)\)</span>. <span class="math inline">\(alive\_post_i\)</span> is the number of days lived after the election for candidate <span class="math inline">\(i\)</span>. <span class="math inline">\(\beta_0\)</span> is the “intercept” of the regression, the average value for the population of <span class="math inline">\(alive\_post_i\)</span> if <span class="math inline">\(alive\_pre_i = 0\)</span>. <span class="math inline">\(\beta_1\)</span> is the “coefficient” of <span class="math inline">\(alive\_pre\)</span>. Each one day increase in <span class="math inline">\(alive\_pre\)</span> is associated with a <span class="math inline">\(\beta_1\)</span> change in <span class="math inline">\(alive\_post\)</span>. Again, this is the value for the population. <span class="math inline">\(\epsilon_i\)</span> is the “error term,” the difference between the days-lived of candidate <span class="math inline">\(i\)</span> and the average days-lived of all candidates. <span class="math inline">\(\epsilon_i\)</span> is normally distributed with a mean of 0 and a standard deviation of <span class="math inline">\(\sigma\)</span>. There are three unknown parameters, similar to the situation we faced in Chapter @ref{three-parameters}.</p>
<!-- Make a single Preceptor Table which we will use for this who section. It will have a single outcome, alive_post, and a bunch of covariates, including all the ones we have saved. It will also have a bunch of rows with missing data, indicating all the people for whom we don't have data, since we are probably interested in applying this more broadly than just US governor candidates who are dead. -->
<p>We can implement this model with <code>stan_glm()</code>.</p>
<div class="sourceCode" id="cb937"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb937-1"><a href="n-parameters.html#cb937-1"></a>fit_gov_<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">stan_glm</span>(<span class="dt">data =</span> ch9_gov,</span>
<span id="cb937-2"><a href="n-parameters.html#cb937-2"></a>                      <span class="dt">formula =</span> alive_post <span class="op">~</span><span class="st"> </span>alive_pre,</span>
<span id="cb937-3"><a href="n-parameters.html#cb937-3"></a>                      <span class="dt">refresh =</span> <span class="dv">0</span>)</span></code></pre></div>
<p>As we discussed in Chapter <a href="three-parameters.html#three-parameters">8</a>, the most common term for a model like this is a “regression.” We have “regressed” <code>alive_post</code>, our dependent variable on <code>alive_pre</code>, our one independent variable.</p>
<p>Most of the time, we are only interested in the parameter values.</p>
<div class="sourceCode" id="cb938"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb938-1"><a href="n-parameters.html#cb938-1"></a><span class="kw">print</span>(fit_gov_<span class="dv">1</span>, <span class="dt">detail =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>##             Median  MAD_SD 
## (Intercept) 26532.8   715.2
## alive_pre      -0.9     0.0
## 
## Auxiliary parameter(s):
##       Median MAD_SD
## sigma 4053.7   87.0</code></pre>
<p>As is almost always the case, <span class="math inline">\(\sigma\)</span> is a nuisance parameter, somethings whose value we are not interested in. This is why <code>stan_glm()</code> refers to it as an “Auxiliary” parameter.</p>
<p>The posterior distributions of <span class="math inline">\(\beta_0\)</span> (the intercept) and <span class="math inline">\(\beta_1\)</span> (the coefficient of <code>alive_pre</code>), on the other hand, are very important. Before looking at the posteriors themselves, let’s see what happens when we place the medians into the model:</p>
<!-- DK: Is it useful to create this formula, with the medians? Why not just show the fitted values graphically. Or discuss the meaning when looking at the regression results. -->
<p><span class="math display">\[ alive\_post_i =  26,524 - 0.9 alive\_pre_i + \epsilon_i\]</span></p>
<p>Consider the intercept. Since our independent variable is <code>alive_pre</code>, the intercept is the <code>alive_post</code> value when <code>alive_pre</code> is zero. Here, we would interpret this intercept as the lifespan of a gubernatorial candidate after the election, if the candidate was alive for zero days prior to the election.</p>
<p>This is, of course, substantively nonsense. No one runs for office on the day they are born. In the next model, we will explore ways of making the intercept more interpretable. In the meantime, the math is the math.</p>
<p>Let’s continue by discussing the coefficient for <code>alive_pre</code>, <span class="math inline">\(\beta_1\)</span>. The median of the posterior, -0.9, represents the slope of the model. For every unit increase in our independent variable, our dependent variable will change by this coefficient. Putting this slope definition in terms of our model, this means that for every additional day a candidate is alive before an election, their lifespan after the election will be 0.9 days lower, on average. If we are given the number of days a candidate lived before the election and want to estimate how long they will live for after, we will multiply the days they were alive prior by this beta of -0.9, then subtract that from the intercept.</p>
<p>This is a descriptive model, not a causal model. Remember our motto from Chapter <a href="rubin-causal-model.html#rubin-causal-model">3</a>: <em>No causation without manipulation.</em> There is no way, for person <span class="math inline">\(i\)</span>, to change the days that she has been alive on Election Day. On the day of this election, she is X days old. There is no way to change that. So, there are not two (or more) potential outcomes. Without more than one potential outcome, there can not be a causal effect.</p>
<p>Given that, it is important to monitor our language. We do not believe that that changes in <code>alive_pre</code> “cause” changes in <code>alive_post</code>. That is obvious. But there are some words and phrases — like “associated with” — which are too close to causal. (And which we are guilty of using just a few paragraphs ago!) Be wary of their use. <em>Always think in terms of comparisons</em> when using a predictive model. We can’t change <code>alive_pre</code> from X to Y for an individual candidate. We can only compare two candidates (or two groups of candidates), one with <code>alive_pre</code> equal to X and the other with <code>alive_pre</code> equal to Y. If our model is correct, such candidates will, on average, differ in <code>alive_post</code> by <span class="math inline">\(\beta_1\)</span> times the difference between X and Y.</p>
<!-- DK: THis is a critical point. Maybe give a precise example? Go through the math slowly, like ModernDive does? -->
<p>Let’s look at the posterior of <span class="math inline">\(\beta_1\)</span>, the coefficient of <code>alive_pre</code>:</p>
<!-- DK: We should standardize what these plots look like, both in this chapter and throughout the book. -->
<div class="sourceCode" id="cb940"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb940-1"><a href="n-parameters.html#cb940-1"></a>fit_gov_<span class="dv">1</span> <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb940-2"><a href="n-parameters.html#cb940-2"></a><span class="st">  </span><span class="kw">as_tibble</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb940-3"><a href="n-parameters.html#cb940-3"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(alive_pre)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb940-4"><a href="n-parameters.html#cb940-4"></a><span class="st">    </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">100</span>) <span class="op">+</span></span>
<span id="cb940-5"><a href="n-parameters.html#cb940-5"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">"Posterior Distribution of the Coefficient of `alive_pre`"</span>,</span>
<span id="cb940-6"><a href="n-parameters.html#cb940-6"></a>         <span class="dt">y =</span> <span class="st">"Probability"</span>,</span>
<span id="cb940-7"><a href="n-parameters.html#cb940-7"></a>         <span class="dt">x =</span> <span class="st">"Coefficient of `alive_pre`"</span>)</span></code></pre></div>
<p><img src="book_temp_files/figure-html/unnamed-chunk-740-1.png" width="672"></p>
<!-- DK: Add some interpretation. Need to explain how the uncertainty in beta_1 is connected to the uncertainty we will see in alive_post, for a given difference (not "change") in alive_pre. -->
<p>Centering is a tool that is used when the model’s intercept does not make substantive sense. To center a model, we pick a constant value, usually the mean of the independent variable, and subtract that constant from every value of the independent variable. This changes the zero point for the variable and shifts the model over.</p>
<p>In this example, we want to center the value for <code>alive_pre</code>, the independent variable. First, we must pick the value that we will center by. Here, we will use the mean of <code>alive_pre</code>. Once we find this value, we will subtract it from every <code>alive_pre</code> value, creating a new variable called <code>alive_pre_centered</code>. We then use <code>alive_pre_centered</code> as the independent variable to model <code>alive_post</code>.</p>
<div class="sourceCode" id="cb941"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb941-1"><a href="n-parameters.html#cb941-1"></a>ch9_gov<span class="op">$</span>alive_pre_centered &lt;-<span class="st"> </span>ch9_gov<span class="op">$</span>alive_pre <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(ch9_gov<span class="op">$</span>alive_pre)</span></code></pre></div>
<div class="sourceCode" id="cb942"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb942-1"><a href="n-parameters.html#cb942-1"></a>fit_gov_<span class="fl">1.</span>centered &lt;-<span class="st"> </span><span class="kw">stan_glm</span>(<span class="dt">data =</span> ch9_gov,</span>
<span id="cb942-2"><a href="n-parameters.html#cb942-2"></a>                      <span class="dt">formula =</span> alive_post <span class="op">~</span><span class="st"> </span>alive_pre_centered,</span>
<span id="cb942-3"><a href="n-parameters.html#cb942-3"></a>                      <span class="dt">refresh =</span> <span class="dv">0</span>)</span>
<span id="cb942-4"><a href="n-parameters.html#cb942-4"></a></span>
<span id="cb942-5"><a href="n-parameters.html#cb942-5"></a><span class="kw">print</span>(fit_gov_<span class="fl">1.</span>centered, <span class="dt">detail =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>##                    Median  MAD_SD 
## (Intercept)        10310.4   120.0
## alive_pre_centered    -0.9     0.0
## 
## Auxiliary parameter(s):
##       Median MAD_SD
## sigma 4054.9   89.0</code></pre>
<p>In this model, we can see that the intercept has increased while the slope has stayed the same. When we interpret this model, we only have to change the definition of the intercept. Rather than the intercept representing the lifespan of a candidate who was alive for zero days before running for governor, it now represents the post-election lifespan of a gubernatorial candidate who was alive for the mean number of days before running. In this instance, our center value is approximately 18,892, so we will use this value in our interpretation. If a candidate was alive for 18,892 days before running for governor (the mean value in this data set), they are expected to live for 10,309 days after the election, on average.</p>
<p>Since all values of the predictor variable decreased by the same amount, the model shifted over but the slope of the linear model did not change. In fact, any linear change in the predictor variables has no effect on other aspects of the model, which is one reason why linear models are so commonly used.</p>
<p>Let’s now regress <code>sex</code> on <code>alive_post</code> to see how candidates’ post-election lifespans differ by sex.</p>
<div class="sourceCode" id="cb944"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb944-1"><a href="n-parameters.html#cb944-1"></a>fit_gov_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">stan_glm</span>(<span class="dt">data =</span> ch9_gov,</span>
<span id="cb944-2"><a href="n-parameters.html#cb944-2"></a>                      <span class="dt">formula =</span> alive_post <span class="op">~</span><span class="st"> </span>sex <span class="op">-</span><span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb944-3"><a href="n-parameters.html#cb944-3"></a>                      <span class="dt">refresh =</span> <span class="dv">0</span>)</span></code></pre></div>
<p>Note that this workflow is similar to professional work. Try one model. Interpret it. Try another model. And then another. There is no one “true” model. There is an infinite space of possible models. Good data science involves an intelligent tour of that space.</p>
<div class="sourceCode" id="cb945"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb945-1"><a href="n-parameters.html#cb945-1"></a><span class="kw">print</span>(fit_gov_<span class="dv">2</span>, <span class="dt">detail =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>##           Median  MAD_SD 
## sexFemale  5838.0  1011.9
## sexMale   10398.5   141.7
## 
## Auxiliary parameter(s):
##       Median MAD_SD
## sigma 4849.6  101.2</code></pre>
<p>In this regression, we use the -1 in the formula to make the output more straightforward, with no intercept to interpret. The math of this model is the same as those we saw in Chapter <a href="three-parameters.html#three-parameters">8</a>:</p>
<p><span class="math display">\[ \underbrace{y_i}_{outcome} = \underbrace{\beta_1 x_{f,i} + \beta_2 x_{m,i}}_{model} + \underbrace{\epsilon_i}_{not\ in\ the\ model}\]</span></p>
<p>where 
<span class="math display">\[x_{f,i}, x_{m,i} \in \{0,1\}\]</span> 
<span class="math display">\[x_{f,i} +  x_{m,i} = 1\]</span> 
<span class="math display">\[\epsilon_i \sim N(0, \sigma^2)\]</span></p>
<!-- DK: Provide more details on what each of the items in the formula means, even though this is a repeat of what we did in chapter 8. -->
<!-- DK: This next section belongs above somewhere, I think. -->
<p>You may recall from algebra that the equation of a line is <span class="math inline">\(y = a + b x\)</span>. It is defined by two coefficients <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>. The intercept coefficient <span class="math inline">\(a\)</span> is the value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x = 0\)</span>. The slope coefficient <span class="math inline">\(b\)</span> for <span class="math inline">\(x\)</span> is the increase in <span class="math inline">\(y\)</span> for every increase of one in <span class="math inline">\(x\)</span>.</p>
<p>However, when defining a regression line, we use slightly different notation: the equation of the regression line is $  = b_0 + b_1 x $. The intercept coefficient is <span class="math inline">\(b_0\)</span>, so <span class="math inline">\(b_0\)</span> is the value of $  $ when <span class="math inline">\(x = 0\)</span>. The slope coefficient for <span class="math inline">\(x\)</span> is <span class="math inline">\(b_1\)</span>, i.e., the increase in $  $ for every increase of one in <span class="math inline">\(x\)</span>. Why do we put a “hat” on top of the <span class="math inline">\(y\)</span>? It’s a form of notation commonly used in regression to indicate that we have a “fitted value,” or the value of <span class="math inline">\(y\)</span> on the regression line for a given <span class="math inline">\(x\)</span> value. This fitted value that falls on the regression line may differ from the observed value of <span class="math inline">\(y\)</span> given that particular <span class="math inline">\(x\)</span> value. The difference between the observed y-value (<span class="math inline">\(y\)</span>) and the predicted, or fitted, y-value ($ $) is called the <em>residual</em>.</p>
<p>Looking back to the regression model we just created, we see that there is no intercept. Instead of having a $ {b_0} $ value, we have <span class="math inline">\(b_1\)</span> and <span class="math inline">\(b_2\)</span> for female and male. This makes things easier to interpret. Without having to add or subtract anything from an intercept, this regression tells us that on average, women are expected to live about 6,000 days after running for governor, and men are expected to live 10,000 days.</p>
<p>This is a strange result. Why would men live twice as long as women after the election. One explanation for this might be that women don’t run for governor until later in life, and therefore are not expected to live as long.</p>
<!-- DK: Weird result, huh? Men live twice as long as women! Useful to discuss why that might be the case. -->
<!-- Perhaps of next is to understand what the intercept is. That is, this model is identical to the previous. -->
<p>Now that we have interpreted the model using a -1 in the formula to get both a <span class="math inline">\(b_1\)</span> value and a <span class="math inline">\(b_2\)</span> value, let’s take away the -1 and regress <code>alive_post</code> on <code>sex</code> to see how our equation changes.</p>
<div class="sourceCode" id="cb947"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb947-1"><a href="n-parameters.html#cb947-1"></a>fit_gov_2a &lt;-<span class="st"> </span><span class="kw">stan_glm</span>(<span class="dt">data =</span> ch9_gov,</span>
<span id="cb947-2"><a href="n-parameters.html#cb947-2"></a>                      <span class="dt">formula =</span> alive_post <span class="op">~</span><span class="st"> </span>sex,</span>
<span id="cb947-3"><a href="n-parameters.html#cb947-3"></a>                      <span class="dt">refresh =</span> <span class="dv">0</span>)</span></code></pre></div>
<div class="sourceCode" id="cb948"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb948-1"><a href="n-parameters.html#cb948-1"></a><span class="kw">print</span>(fit_gov_2a, <span class="dt">detail =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>##             Median MAD_SD
## (Intercept) 5836.7 1062.6
## sexMale     4558.1 1076.7
## 
## Auxiliary parameter(s):
##       Median MAD_SD
## sigma 4852.1  109.0</code></pre>
<p>From this result, we can see that we no longer have a value for female, however we do have an intercept. In this regression our mathematical regression formula is <span class="math inline">\(\hat{alive\_post_i} = b_0 + b_1 x_{m, i}\)</span>. $ b_0 $ is our intercept value which here would be 5875. You may notice that this is very similar to the female value from before. In this type of model, our intercept represents the characteristic of the variable that is left unrepresented in the model. Here our slope, or $ b_1 $ value is for when the candidate is male. Therefore, we can infer that the intercept value represents those who are not male: females.</p>
<p>When the candidate is a male, we add the beta for male to the intercept value, which gives us the average lifespan of a male gubernatorial candidate after an election. As we can see from adding <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>, this value is the same as what we got for males in the previous model.</p>
<!-- DK: Be careful with notation! b_1 in the no-intercept model is different from b_1 in the last model! Explain this here. -->
<!-- DK: Clean up and explain this plot. It is relevant. -->
<p><img src="book_temp_files/figure-html/unnamed-chunk-747-1.png" width="672"></p>
<p>For our next mode, let’s include both <code>sex</code> and <code>alive_pre</code> in the regression.</p>
<div class="sourceCode" id="cb950"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb950-1"><a href="n-parameters.html#cb950-1"></a>fit_gov_<span class="dv">3</span> &lt;-<span class="st"> </span><span class="kw">stan_glm</span>(<span class="dt">data =</span> ch9_gov,</span>
<span id="cb950-2"><a href="n-parameters.html#cb950-2"></a>                      <span class="dt">formula =</span> alive_post <span class="op">~</span><span class="st"> </span>sex <span class="op">+</span><span class="st"> </span>alive_pre,</span>
<span id="cb950-3"><a href="n-parameters.html#cb950-3"></a>                      <span class="dt">refresh =</span> <span class="dv">0</span>)</span></code></pre></div>
<div class="sourceCode" id="cb951"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb951-1"><a href="n-parameters.html#cb951-1"></a><span class="kw">print</span>(fit_gov_<span class="dv">3</span>, <span class="dt">detail =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>##             Median  MAD_SD 
## (Intercept) 24068.0  1196.8
## sexMale      2288.8   902.7
## alive_pre      -0.8     0.0
## 
## Auxiliary parameter(s):
##       Median MAD_SD
## sigma 4048.5   89.6</code></pre>
<!-- DK: Cool, eh? It is (mostly?) an age effect! Controlling for age at the election, women live about as long as men, but they are much more likely be candidates as an older age. Again, what we are doing is slowly building more complex models, understanding what they mean. -->
<!-- Also, note that this is a "parallel slopes" model. Explain slowly what that means.  Create a plot. -->
<!-- Side note: I would have thought that overlapping CIs for male/female would equate to insignificance of sex dummy when the regression includes a intercept. But that does not seem to be the case. Am I missing something? -->
<!-- Make the graphic which shows two parallel lines, by calling two layers of geom_smooth().  -->
<!-- With this as warm-up, we are now in a position to explore interactions. -->
<div class="sourceCode" id="cb953"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb953-1"><a href="n-parameters.html#cb953-1"></a>fit_gov_<span class="dv">4</span> &lt;-<span class="st"> </span><span class="kw">stan_glm</span>(<span class="dt">data =</span> ch9_gov,</span>
<span id="cb953-2"><a href="n-parameters.html#cb953-2"></a>                      <span class="dt">formula =</span> alive_post <span class="op">~</span><span class="st"> </span>sex<span class="op">*</span>alive_pre,</span>
<span id="cb953-3"><a href="n-parameters.html#cb953-3"></a>                      <span class="dt">refresh =</span> <span class="dv">0</span>)</span></code></pre></div>
<div class="sourceCode" id="cb954"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb954-1"><a href="n-parameters.html#cb954-1"></a><span class="kw">print</span>(fit_gov_<span class="dv">4</span>, <span class="dt">detail =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>##                   Median  MAD_SD 
## (Intercept)        7331.4  7989.8
## sexMale           19248.6  8056.4
## alive_pre            -0.1     0.4
## sexMale:alive_pre    -0.8     0.4
## 
## Auxiliary parameter(s):
##       Median MAD_SD
## sigma 4042.5   88.3</code></pre>
<!-- DK: Take your time explaining what this means! It is not trivial. Note that this is a non-parallel slopes model. -->
<div class="sourceCode" id="cb956"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb956-1"><a href="n-parameters.html#cb956-1"></a>fit_gov_<span class="dv">5</span> &lt;-<span class="st"> </span><span class="kw">stan_glm</span>(<span class="dt">data =</span> ch9_gov,</span>
<span id="cb956-2"><a href="n-parameters.html#cb956-2"></a>                      <span class="dt">formula =</span> alive_post <span class="op">~</span><span class="st"> </span>state <span class="op">+</span><span class="st"> </span>sex<span class="op">*</span>alive_pre,</span>
<span id="cb956-3"><a href="n-parameters.html#cb956-3"></a>                      <span class="dt">refresh =</span> <span class="dv">0</span>,</span>
<span id="cb956-4"><a href="n-parameters.html#cb956-4"></a>                      <span class="dt">iter =</span> <span class="dv">10000</span>)</span></code></pre></div>
<div class="sourceCode" id="cb957"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb957-1"><a href="n-parameters.html#cb957-1"></a><span class="kw">print</span>(fit_gov_<span class="dv">5</span>, <span class="dt">detail =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>##                     Median  MAD_SD 
## (Intercept)          5851.4  7862.6
## stateAlaska          1098.8  1430.1
## stateArizona         2924.8  1169.8
## stateArkansas         533.7  1190.5
## stateCalifornia      2014.2  1268.9
## stateColorado        1503.0  1253.3
## stateConnecticut     1036.8  1273.3
## stateDelaware        3112.8  1308.6
## stateFlorida        -1540.9  1380.8
## stateGeorgia         1802.6  1452.5
## stateHawaii          1591.1  1540.6
## stateIdaho           1727.4  1285.1
## stateIllinois        -144.8  1349.8
## stateIndiana         1246.4  1264.7
## stateIowa             951.9  1193.2
## stateKansas          -136.7  1194.5
## stateKentucky        1497.9  1309.5
## stateLouisiana       1432.7  1498.8
## stateMaine           2136.1  1342.0
## stateMaryland        1684.3  1261.1
## stateMassachusetts     98.4  1181.1
## stateMichigan       -1162.8  1231.1
## stateMinnesota       1649.1  1187.5
## stateMississippi      787.0  1335.8
## stateMissouri         489.9  1352.7
## stateMontana          856.7  1296.3
## stateNebraska         808.8  1204.9
## stateNevada          1517.4  1371.2
## stateNew Hampshire   1310.8  1209.5
## stateNew Jersey       391.4  1321.6
## stateNew Mexico      1025.9  1177.3
## stateNew York         875.9  1246.3
## stateNorth Carolina -1415.7  1462.7
## stateNorth Dakota    2150.3  1238.6
## stateOhio            2191.9  1224.1
## stateOklahoma        -568.8  1350.7
## stateOregon           229.8  1266.0
## statePennsylvania    1267.4  1270.0
## stateRhode Island    1952.3  1121.1
## stateSouth Carolina  2465.9  1373.0
## stateSouth Dakota   -1838.8  1183.9
## stateTennessee       -441.9  1311.0
## stateTexas           1191.1  1166.1
## stateUtah            1201.0  1274.6
## stateVermont          547.2  1173.4
## stateVirginia        2547.0  1435.3
## stateWashington      2777.0  1273.6
## stateWest Virginia   2420.0  1306.8
## stateWisconsin       2456.3  1183.9
## stateWyoming         -517.4  1284.6
## sexMale             20083.4  7888.4
## alive_pre              -0.1     0.4
## sexMale:alive_pre      -0.8     0.4
## 
## Auxiliary parameter(s):
##       Median MAD_SD
## sigma 3961.0   87.5</code></pre>
<!-- DK: Need to modify this to only show one of the more interesting state coefficients. (Although we might show all the state pdfs in the graphic.) This a good place to discuss shrinkage, which is what is happening here. And that is probably enough models. -->
</div>
<div id="temperance" class="section level2">
<h2>
<span class="header-section-number">9.4</span> Temperance</h2>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:unnamed-chunk-754"></span>
<img src="other/images/Temperance.jpg" alt="Temperance" width="960"><!--
<p class="caption marginnote">-->FIGURE 9.4: Temperance<!--</p>-->
<!--</div>--></span>
</p>
</div>
<div id="eda-of-shaming" class="section level2">
<h2>
<span class="header-section-number">9.5</span> EDA of <code>shaming</code>
</h2>
<!-- Use print(fit_obj, digits = 4) if you need to see more digits. -->
<!-- Models to use-->
<!-- primary_06 ~ sex - 1 -->
<!-- primary_06 ~ age -->
<!-- primary_06 ~ treatment - 1 (plot all five posteriors together) -->
<!-- primary_06 ~ sex + solo + treatment -->
<!-- primary_06 ~ sex + solo + treatment + solo * treatment -->
<p>Imagine you are running for Governor and want to do a better job of getting your voters to vote. You recently read about a large-scale experiment showing the effect of sending out a voting reminder that “shames” citizens who do not vote. You are considering sending out a “shaming” voting reminder yourself. What will happen if you do? Will more voters show up to the polls? Additionally, on the day of the election a female citizen is randomly selected. What is the probability she will vote?</p>
<p>Consider a new data set, <code>shaming</code>, corresponding to an experiment carried out by Gerber, Green, and Larimer (2008) titled “Social Pressure and Voter Turnout: Evidence from a Large-Scale Field Experiment”. This experiment used several hundred thousand registered voters and a series of mailings to determine the effect of social pressure on voter turnout.</p>
<p>Let’s now do another EDA, starting off by running <code>glimpse()</code>.</p>
<div class="sourceCode" id="cb959"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb959-1"><a href="n-parameters.html#cb959-1"></a><span class="kw">glimpse</span>(shaming)</span></code></pre></div>
<pre><code>## Rows: 344,084
## Columns: 10
## $ sex         &lt;chr&gt; "Male", "Female", "Male", "Female", "Female", "Male", "Fe…
## $ birth_year  &lt;int&gt; 1941, 1947, 1951, 1950, 1982, 1981, 1959, 1956, 1968, 196…
## $ primary_02  &lt;chr&gt; "Yes", "Yes", "Yes", "Yes", "Yes", "No", "Yes", "Yes", "Y…
## $ general_02  &lt;chr&gt; "Yes", "Yes", "Yes", "Yes", "Yes", "No", "Yes", "Yes", "N…
## $ primary_04  &lt;chr&gt; "No", "No", "No", "No", "No", "No", "No", "No", "No", "No…
## $ general_04  &lt;chr&gt; "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "…
## $ treatment   &lt;fct&gt; Civic Duty, Civic Duty, Hawthorne, Hawthorne, Hawthorne, …
## $ primary_06  &lt;int&gt; 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, …
## $ hh_size     &lt;int&gt; 2, 2, 3, 3, 3, 3, 3, 3, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, …
## $ no_of_names &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…</code></pre>
<p>Here we see that <code>glimpse()</code> gives us a look at the raw data contained within the <code>shaming</code> data set. At the very top of the output, we can see the number of rows and columns, or observations and variables respectively. We see that there are 344,084 observations, with each row corresponding to a unique respondent. The “Columns: 10” tells us that there are 10 variables within this data set. Below this, we see a cutoff version of the entire data set that has the variables on the left as rows and the observations as a list separated by commas, as compared to the tibble output that presents with the variables as columns and the observations as rows running horizontally.</p>
<!-- It may be worth mentioning that general_04 is always "yes", unlike all the other voting history variables which have values of "yes" and "no". Why is that? I *think* that this is caused by their sampling plan. They found all the people who voted in the 2004 general election. Then, the authors found their history. As we would expect, those people had sometimes voted in the past and sometime not. Then, the authors sent the mailing. The key dependent variable, primary_06, is coding 0/1, since that makes doing the statistics easier. -->
<p>From this summary, we get an idea about some of the variables we will be dealing with. Some variables that will be of interest to us are <code>sex</code>, <code>hh_size</code>, and <code>primary_06</code>. The variable <code>hh_size</code> tells us the size of the respondent’s household, and <code>primary_06</code> tells us whether or not the respondent voted in the 2006 Primary election.</p>
<p>There are a few things to note while exploring this data set. You may – or may not – have noticed that the only response to the <code>general_04</code> variable is “Yes”. In their published article, the authors note that “Only registered voters who voted in November 2004 were selected for our sample” (Gerber, Green, Larimer, 2008). After this, the authors found their history then sent out the mailings.</p>
<p>It is also important to identify the dependent variable and its meaning. In this shaming experiment, the dependent variable is <code>primary_06</code>, which is a variable coded either 0 or 1 for whether or not the respondent voted in the 2006 primary election. This is the dependent variable because the authors are trying to measure the effect that the treatments have on the proportion of people who vote in the 2006 general election.</p>
<!-- HV: Should I include discussion of the left-hand variable (treatment?) here? Or wait until we move into the regressions? -->
<p>The voting results from other years, such as 2002 and 2004, are of less interest to us and can be removed from the abbreviated data set. In addition to removing <code>general_04</code>, <code>primary_02</code>, <code>general_02</code>, or <code>primary_04</code>, we also will not be taking particular interest in <code>birth_year</code>, or <code>no_of_names</code> within this chapter.
<!-- HV: should I explain why we are not using any of these variables? why they are not of great use to us? --></p>
<p>By narrowing down the set of variables we are looking at and investigating, we will find more meaningful relationships among them. However, we have not yet discussed the most important variable of them all: <code>treatment</code>. The <code>treatment</code> variable is a factor variable with 5 levels, including the control. Since we are curious as to how sending mailings affects voter turnout, the treatment variable will tell us about the impact each type of mailing can make. Let’s start off by taking a broad look at the different treatments.
<!-- HV: Is it okay to say the first sentence of this paragraph? --></p>
<div class="sourceCode" id="cb961"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb961-1"><a href="n-parameters.html#cb961-1"></a>shaming <span class="op">%&gt;%</span></span>
<span id="cb961-2"><a href="n-parameters.html#cb961-2"></a><span class="st">  </span><span class="kw">count</span>(treatment)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##   treatment       n
##   &lt;fct&gt;       &lt;int&gt;
## 1 Civic Duty  38218
## 2 Hawthorne   38204
## 3 Control    191243
## 4 Self        38218
## 5 Neighbors   38201</code></pre>
<p>Four types of treatments were used in the experiment, with voters receiving one type of mailing. All of the mailing treatments carried the message, “DO YOUR CIVIC DUTY - VOTE!”.</p>
<p>The first treatment, Civic Duty, also read, “Remember your rights and responsibilities as a citizen. Remember to vote.” This message acted as a baseline for the other treatments, since it carried a message very similar to the one displayed on all the mailings.</p>
<p>In the second treatment, Hawthorne, households received a mailing which told the voters that they were being studied and their voting behavior would be examined through public records. This adds a small amount of social pressure to the households receiving this mailing.</p>
<p>In the third treatment, Self, the mailing includes the recent voting record of each member of the household, placing the word “Voted” next to their name if they did in fact vote in the 2004 election or a blank space next to the name if they did not. In this mailing, the households were also told, “we intend to mail an updated chart” with the voting record of the household members after the 2006 primary. By emphasizing the public nature of voting records, this type of mailing exerts more social pressure on voting than the Hawthorne treatment.</p>
<p>The fourth treatment, Neighbors, provides the household members’ voting records, as well as the voting records of those who live nearby. This mailing also told recipients, “we intend to mail an updated chart” of who voted in the 2006 election.</p>
<p>For now, let’s focus on a subset of the data.</p>
<div class="sourceCode" id="cb963"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb963-1"><a href="n-parameters.html#cb963-1"></a>ch9 &lt;-<span class="st"> </span>shaming <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb963-2"><a href="n-parameters.html#cb963-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">solo =</span> <span class="kw">ifelse</span>(hh_size <span class="op">==</span><span class="st"> </span><span class="dv">1</span>, <span class="ot">TRUE</span>, <span class="ot">FALSE</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb963-3"><a href="n-parameters.html#cb963-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age =</span> <span class="dv">2006</span> <span class="op">-</span><span class="st"> </span>birth_year) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb963-4"><a href="n-parameters.html#cb963-4"></a><span class="st">  </span><span class="kw">select</span>(primary_<span class="dv">06</span>, treatment, solo, sex, age)</span></code></pre></div>
<p>We create the variable <code>solo</code>, which is TRUE for voters who live alone and FALSE for those that do not. We are curious to see if the treatment effect, if any, is the same for voters who live alone as it is for those who do not.</p>
<div class="sourceCode" id="cb964"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb964-1"><a href="n-parameters.html#cb964-1"></a>ch9 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb964-2"><a href="n-parameters.html#cb964-2"></a><span class="st">  </span><span class="kw">skim</span>()</span></code></pre></div>
<p><!--
<caption>--><span class="marginnote shownote"><span id="tab:unnamed-chunk-758">TABLE 9.2: </span>Data summary</span><!--</caption>--></p>
<table><tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">Piped data</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">344084</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">factor</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">logical</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">2</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody></table>
<p><strong>Variable type: character</strong></p>
<table>
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">sex</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr></tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table>
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="left">ordered</th>
<th align="right">n_unique</th>
<th align="left">top_counts</th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">treatment</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">FALSE</td>
<td align="right">5</td>
<td align="left">Con: 191243, Civ: 38218, Sel: 38218, Haw: 38204</td>
</tr></tbody>
</table>
<p><strong>Variable type: logical</strong></p>
<table>
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="left">count</th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">solo</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0.14</td>
<td align="left">FAL: 296250, TRU: 47834</td>
</tr></tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">primary_06</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0.32</td>
<td align="right">0.46</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">▇▁▁▁▃</td>
</tr>
<tr class="even">
<td align="left">age</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">49.79</td>
<td align="right">14.45</td>
<td align="right">20</td>
<td align="right">41</td>
<td align="right">50</td>
<td align="right">59</td>
<td align="right">106</td>
<td align="left">▃▇▅▁▁</td>
</tr>
</tbody>
</table>
<!-- DK: Add discussion of what you see here. No need to drop missing values since there aren't any. I think this next discussion can be dropped. --><p>While some summarizing commands such as <code>glimpse()</code> gives us a good look at the possible values for the variables, it is difficult to read it in terms of individual observations. Recall that the <em>observational unit</em> is what is being measured. With the <code>shaming</code> data set, the observational unit would be the voter respondent. To get a better sense of some respondents’ information, let’s use <code>sample_n()</code> to gather a random sample of <em>n</em> observations from the data set.
<!-- HV: Does this belong here? --></p>
<div class="sourceCode" id="cb965"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb965-1"><a href="n-parameters.html#cb965-1"></a>ch9 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb965-2"><a href="n-parameters.html#cb965-2"></a><span class="st">  </span><span class="kw">sample_n</span>(<span class="dv">10</span>)</span></code></pre></div>
<pre><code>## # A tibble: 10 x 5
##    primary_06 treatment  solo  sex      age
##         &lt;int&gt; &lt;fct&gt;      &lt;lgl&gt; &lt;chr&gt;  &lt;dbl&gt;
##  1          1 Control    FALSE Female    60
##  2          0 Self       FALSE Female    53
##  3          1 Hawthorne  FALSE Male      44
##  4          1 Control    FALSE Male      50
##  5          1 Hawthorne  FALSE Female    29
##  6          1 Control    FALSE Male      46
##  7          1 Control    FALSE Female    48
##  8          0 Civic Duty FALSE Male      52
##  9          0 Neighbors  FALSE Male      48
## 10          1 Control    FALSE Male      57</code></pre>
<p>Now we have a table with 5 random observations and the respondents’ information in a regular table output. By taking a few random samples, we may start to see some patterns within the data.</p>
<p>Now we have a table with 5 random observations and the respondents’ information in a regular table output. By taking a few random samples, we may start to see some patterns within the data. Do you notice anything in particular about the variable <code>treatment</code>?</p>
<p>One other helpful summarizing technique we can use is <code>skim()</code>. To make the information it contains simpler, we will only be looking at three variables: <code>primary_06</code>, <code>treatment</code>, and <code>sex</code>.</p>
<div class="sourceCode" id="cb967"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb967-1"><a href="n-parameters.html#cb967-1"></a>shaming <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb967-2"><a href="n-parameters.html#cb967-2"></a><span class="st">  </span><span class="kw">select</span>(primary_<span class="dv">06</span>, treatment, sex) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb967-3"><a href="n-parameters.html#cb967-3"></a><span class="st">  </span><span class="kw">skim</span>()</span></code></pre></div>
<p><!--
<caption>--><span class="marginnote shownote"><span id="tab:unnamed-chunk-760">TABLE 9.3: </span>Data summary</span><!--</caption>--></p>
<table><tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">Piped data</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">344084</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">3</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">factor</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody></table>
<p><strong>Variable type: character</strong></p>
<table>
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">sex</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr></tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table>
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="left">ordered</th>
<th align="right">n_unique</th>
<th align="left">top_counts</th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">treatment</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">FALSE</td>
<td align="right">5</td>
<td align="left">Con: 191243, Civ: 38218, Sel: 38218, Haw: 38204</td>
</tr></tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">primary_06</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0.32</td>
<td align="right">0.46</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="left">▇▁▁▁▃</td>
</tr></tbody>
</table>
<p>By running the <code>skim()</code> command, we get a summary of the data set as a whole, as well as the types of variables and individual variable summaries. At the top we see the number of columns and rows within the selected data set. Below this we are given a list with the different types of variables, or columns, and how often they appear within the data we are skimming. Following this, the variables are then separated by their column type, and we are given individual summaries based on the type.</p>
<!-- 2) `primary_06` as a function of `treatment` and `solo` and of their interaction. We will build up this model step-by-step, very similar to how we explored the effect of treatment in chapter 8. But we go deeper because  we are learning about interactions. Key thing is to go through all the themes.Rmd issues, at least until prediction. Note that this situation is different from Chapter 8 in that fitted values and predicted values are not the same thing! The fitted value, for a combination of values for treatment and solo, is something 0.30, meaning that 30% of the people in this bucket votes. But the predicted value must be 0 or 1. Either you voted or you didn't. This example is clearly causal and so you need a Rubin Table with 4 potential outcome columns. The key difference in this chapter is that we are using lots of right hand side variables, both continuous and discrete. -->
<!-- 3) EDA of `nes`. This can be fairly quick. Again, we won't use all the variables. Only discuss the ones we do use. One of the variables should be year. We want to show off Gelman's trick by plotting things by year. -->
<!-- 4) We are making a predictive model of what as a function of what other stuff? Want to use a continuous variable and some discrete variables as well. Interactions to.  -->
<!-- 5) I don't think we bother with a scenario which requires a bootstrap. Or should we?  -->
<!-- 6) Prediction. How do we use our model to make predictions? Bring the discussion back to the way that we opened the chapter with a problem. -->
<p>Having created models with one parameter in Chapter <a href="one-parameter.html#one-parameter">6</a> and two parameters in Chapter <a href="two-parameters.html#two-parameters">7</a>, you are now ready to make the jump to <span class="math inline">\(N\)</span> parameters. The more parameters we include in our models, the more flexible they can become. But we must be careful of <em>overfitting</em>, of making models which are inaccurate because they don’t have enough data to accurately estimate those parameters. The tension between overfitting and underfitting is central to the practice of data science.</p>
<!-- DK: Note that this situation is different from Chapter 8 in that fitted values and predicted values are not the same thing! The fitted value, for a combination of values for treatment and solo, is something 0.30, meaning that 30% of the people in this bucket votes. But the predicted value must be 0 or 1. Either you voted or you didn't. This example is clearly causal and so you need a Rubin Table with 5 potential outcome columns. The key difference in this chapter is that we are using lots of right hand side variables, both continuous and discrete. -->
<div id="wisdom-1" class="section level3">
<h3>
<span class="header-section-number">9.5.1</span> Wisdom</h3>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:unnamed-chunk-761"></span>
<img src="other/images/Wisdom.jpg" alt="Wisdom" width="1280"><!--
<p class="caption marginnote">-->FIGURE 9.5: Wisdom<!--</p>-->
<!--</div>--></span>
</p>
</div>
<div id="justice" class="section level3">
<h3>
<span class="header-section-number">9.5.2</span> Justice</h3>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:unnamed-chunk-762"></span>
<img src="other/images/Justice.jpg" alt="Justice" width="960"><!--
<p class="caption marginnote">-->FIGURE 9.6: Justice<!--</p>-->
<!--</div>--></span>
</p>
</div>
<div id="courage" class="section level3">
<h3>
<span class="header-section-number">9.5.3</span> Courage</h3>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:unnamed-chunk-763"></span>
<img src="other/images/Courage.jpg" alt="Courage" width="1024"><!--
<p class="caption marginnote">-->FIGURE 9.7: Courage<!--</p>-->
<!--</div>--></span>
</p>
</div>
<div id="temperance-1" class="section level3">
<h3>
<span class="header-section-number">9.5.4</span> Temperance</h3>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:unnamed-chunk-764"></span>
<img src="other/images/Temperance.jpg" alt="Temperance" width="960"><!--
<p class="caption marginnote">-->FIGURE 9.8: Temperance<!--</p>-->
<!--</div>--></span>
</p>
</div>
</div>
<div id="causal-effects-of-treament" class="section level2">
<h2>
<span class="header-section-number">9.6</span> Causal Effects of <code>treament</code>
</h2>
<p>We will now be looking into the causal effect of the treatment variable on the 2006 primary election. To start, let’s build a model using <code>stan_glm()</code> followed by a regression table.</p>
<div class="sourceCode" id="cb968"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb968-1"><a href="n-parameters.html#cb968-1"></a><span class="co"># obj.1 &lt;- stan_glm(data = shaming, </span></span>
<span id="cb968-2"><a href="n-parameters.html#cb968-2"></a><span class="co">#                 formula = primary_06 ~ treatment - 1, </span></span>
<span id="cb968-3"><a href="n-parameters.html#cb968-3"></a><span class="co">#                 family = gaussian(), </span></span>
<span id="cb968-4"><a href="n-parameters.html#cb968-4"></a><span class="co">#                 refresh = 0)</span></span></code></pre></div>
<p>This table shows us each of the five treatments and their beta coefficients, along with a 95% Confidence Interval for these coefficients. The Control provides us with a baseline.</p>
<!-- Talk about what these results mean.  Then, create the same model but with a different structure. -->
<div class="sourceCode" id="cb969"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb969-1"><a href="n-parameters.html#cb969-1"></a><span class="co"># obj.2 &lt;- stan_glm(data = shaming, </span></span>
<span id="cb969-2"><a href="n-parameters.html#cb969-2"></a><span class="co">#                 formula = primary_06 ~ treatment, </span></span>
<span id="cb969-3"><a href="n-parameters.html#cb969-3"></a><span class="co">#                 family = gaussian(), </span></span>
<span id="cb969-4"><a href="n-parameters.html#cb969-4"></a><span class="co">#                 refresh = 0)</span></span></code></pre></div>
<!-- Explain how these two models are the same, except in how they define the parameters. Show us the math like Gelman does. Write down the math. For simple. -->
<!-- Once we talk about these things --- and, again, this is exactly what we have talked about in chapter 8 --- we can do a bit more. Like discuss how we are using 99%, because there is nothing magical aboyt 95%, other than convention. I also think it would be fun to show a nice graphic of this, highlighting how the estimates for Civic and Hawthorne overlap.  -->
<div id="interactions" class="section level3">
<h3>
<span class="header-section-number">9.6.1</span> Interactions</h3>
<!-- This is new. With only two parameters, we can't really look at interaction effects. Need to discuss interaction effects in general. Also, note that heterogenous treatment effects are the same thing as interaction effects that involve a treatment effect as one of the variables.  -->
<!-- Feel free to build up this code, and other examples, more slowly than I am doing it here. -->
<div class="sourceCode" id="cb970"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb970-1"><a href="n-parameters.html#cb970-1"></a><span class="co"># obj.3 &lt;- stan_glm(data = shaming, </span></span>
<span id="cb970-2"><a href="n-parameters.html#cb970-2"></a><span class="co">#                 formula = primary_06 ~ sex + treatment + sex:treatment, </span></span>
<span id="cb970-3"><a href="n-parameters.html#cb970-3"></a><span class="co">#                 family = gaussian(), </span></span>
<span id="cb970-4"><a href="n-parameters.html#cb970-4"></a><span class="co">#                 refresh = 0)</span></span></code></pre></div>
<!-- Takes a while to explain what all this means. -->
<!-- Two key issues: 1) Interpreting lots of parameters in a model. interactions, heterogenous treatment effects. shaming using lm().  -->
<!-- Treatment effect is not the same thing as a coefficient. -->
<!-- 
intercept

Interactions --- use: income ~ party*something

heterogeneous treatment effects --- use:  att_start ~ treatment*something 
just a fancy way of saying interaction effects, but with a variable which us causal


What problems do we face? All the things that make modeling difficult. Why is this so hard? -->
<!-- Centering. -->
<!-- Might naively just take the value for each bucket. But that overfits! Need to put down some structure, like ordering. -->
<!-- income category, party id, pooling, age, -->
<!-- overfitting/underfitting bias/variance -->
<!-- We must have left bootstrapping behind by now. No more bootstraps, at least for the purpose of calculating uncertainty. (We will use it later for the purpose of out-of-sample testing and avoiding overfitting.) Key lesson is that overfitting is easy. You can't just estimate a value for each cell. You need to smooth and borrow strength. Of course, the only way to do that is with a Bayesian approach. Right? We don't want to get into hacked likelihood approaches. -->
<!-- cces looks perfect for this project. There are 400,000 rows, so it seems like you ought to have plenty of data for anything you want, but once you realize there are 51 states and 10 years, things get sparse fast. We only have 15 observations, for example, for Wyoming in 2007. Once you start subsetting by race and education, you have no choice but to start borrowing strength.  -->
<!-- So, just what will we use? rstanarm(). If so (and if we have not introduced it earlier), we can begin with seeing how it is similar to lm() and then expand. This means that, in one paramter chapter, we should be doing lm( ~ 1). In two parameter, lm( ~ treatment) --- if treatment is zero one --- or, perhaps better, lm( ~ -1 + treatment) if treatment is a factor/character with two levels. We might also have introduced  -->
<!-- MF: Is basic structure for this chapter meant to be [1] life span section, [2] shame section, and [3] interactions? -->

<!-- Add a couple more of the chapters? Or maybe put them in chapter 11? -->
<!-- Cut the recipe, bake, stuff? Not really needed for chapters 11 and 12. -->
<!-- Replace lm() with stan_glm()? -->
<!-- Get rid of multi-category example discussion? No! Hope to do pyTorch at some point. -->
<!-- 2) Each section ends with the code we have done. That seems redundant and confusing. -->
<!-- 3) Need to make the approach here mesh with the approaches used in chapter 11 and 12. What can we cut from here that is not used? How should we change later chapters to be consistent with this modern approach? -->
<!-- 4) I am concerned about the ames_snippets.R code used in the original but, maybe, not needed here. -->
<!-- 6) Many sections begun with a weird code chunk. These should be cleaned up and organized. -->
<!-- 7) Deal with the missing references. Need to add them to the bib. -->
<!-- 8) Maybe follow their example with r pkg(dplyr) instead of **dplyr**. -->
</div>
</div>
</div></body></html>

<p style="text-align: center;">
<a href="three-parameters.html"><button class="btn btn-default">Previous</button></a>
<a href="model-choice.html"><button class="btn btn-default">Next</button></a>
</p>
<p class="build-date">Page built: 
2020-10-19
</p>
</div>
</div>



</body>
</html>
