<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="Chapter 8 Three Parameters | Gov 50: Data" />
<meta property="og:type" content="book" />



<meta name="github-repo" content="davidkane9/PPBDS" />



<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="Chapter 8 Three Parameters | Gov 50: Data">

<title>Chapter 8 Three Parameters | Gov 50: Data</title>

<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/envisioned.css" rel="stylesheet" />
<link href="libs/msmb-css-0/msmb.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);

e.style.display = ((e.style.display!='none') ? 'none' : 'block');

if(f.classList.contains('fa-plus-square')) {
    f.classList.add('fa-minus-square')
    f.classList.remove('fa-plus-square')
} else {
    f.classList.add('fa-plus-square')
    f.classList.remove('fa-minus-square')
}

}
</script>
<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<link href="libs/str_view-0.1.0/str_view.css" rel="stylesheet" />
<script src="libs/str_view-binding-1.4.0/str_view.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }

code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul class="navbar">
<li class="msmb"><p class="title">Gov 50: Data<p><p class="author"></p>
<li class="dropdown" style="float:right">
<a href="javascript:void(0)" class="dropbtn">&#x25BE; Chapters</a>
<div class="dropdown-content">
<a href="index.html"></a>
<a href="preamble.html">Preamble</a>
<a href="shopping-week.html">Shopping Week</a>
<a href="visualization.html"><span class="toc-section-number">1</span> Visualization</a>
<a href="wrangling.html"><span class="toc-section-number">2</span> Wrangling</a>
<a href="rubin-causal-model.html"><span class="toc-section-number">3</span> Rubin Causal Model</a>
<a href="functions.html"><span class="toc-section-number">4</span> Functions</a>
<a href="probability.html"><span class="toc-section-number">5</span> Probability</a>
<a href="one-parameter.html"><span class="toc-section-number">6</span> One Parameter</a>
<a href="two-parameters.html"><span class="toc-section-number">7</span> Two Parameters</a>
<a id="active-page" href="three-parameters.html"><span class="toc-section-number">8</span> Three Parameters</a><ul class="toc-sections">
<li class="toc"><a href="#eda-for-trains"> EDA for <code>trains</code></a></li>
<li class="toc"><a href="#age-as-a-function-of-party"> <code>age</code> as a function of <code>party</code></a></li>
<li class="toc"><a href="#NA"> <code>att_end</code> as a function of <code>treatment</code></a></li>
</ul>
<a href="n-parameters.html"><span class="toc-section-number">9</span> N Parameters</a>
<a href="model-choice.html"><span class="toc-section-number">10</span> Model Choice</a>
<a href="continuous-response.html"><span class="toc-section-number">11</span> Continuous Response</a>
<a href="discrete-response.html"><span class="toc-section-number">12</span> Discrete Response</a>
<a href="appendices.html">Appendices</a>
<a href="tools.html">Tools</a>
<a href="shiny.html">Shiny</a>
<a href="maps.html">Maps</a>
<a href="animation.html">Animation</a>
<a href="references.html">References</a>
</div>
</li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><div id="three-parameters" class="section level1">
<h1>
<span class="header-section-number">Chapter 8</span> Three Parameters</h1>
<p><em>This chapter is still very much a draft.</em> Come back in a few weeks for a better version.</p>
<!--   2.1) Wisdom -->
<!--   This section can be rather short. There are two aspects to be discussed: Whether our data is appropriate for answering our research question and whether there are ethical concerns. Stick to the points outlined by Gelman. Begin by discussing possible problems with the data set on hand, in particular the 'age' and 'party' variables. Also consider how other variables might impact the usefulness of these two. Make sure to address both content-related (does this variables tell us what we're looking for?) and methodological problems (is the assignment mechanism problematic, can the scale lead to problems?). This was already discussed on C3, so have a look at this before doing all this from scratch. -->
<!--   2.2) Justice -->
<!--   This section consists of two parts. First, we need to become aware of the purpose of our our model - in this section, it is about making a prediction. Explain why that is, and how this shows in the Preceptor able. Start with and infinite one, then drop any irrelevant rows and columns to arrive at the ideal Preceptor table. Replace unknown rows with question marks to get the actual table. Again, have a look at C3 before doing this. -->
<!--   Second, show the mathematical model. Start by repeating the generic regression equation shown in the math section of C3. Then, write the actual regression equation we will use to create our model in this chapter. Instead of just stopping here like in previous chapters, we will now explain what it actually means. Again, no need to talk about the Bayesian-specific stuff like priors. Start with a scatterplot, then add a regression line. Explain how the stuff in the plot corresponds to the equation. Give some examples. -->
<!--   2.3) Courage -->
<!--   This section consists of two subparts. First, we need to explain the fitted model. Estimate the model shown before using stan_glm().  Then, create a scatterplot with the estimated regression line. Explain the output by referring to the plot.  -->
<!--   Second, explain the unmodeled variation. It is, on average, zero - without this assumption, our model would be useless. Explain why this does not hold for (almost) any individual observation, i.e. what residuals are. Give some examples. Finally, create a histogram each for the distribution of y hat, the two regression coefficients, and the residuals. Arrange them in this very order, and possibly put the regression equation below to show how this relates to the model. -->
<!--   2.4) Temperance -->
<!--   We have three sections here. First, make some predictions using predict(), posterior_predict(), and posterior linpred. Explain what the output means.  -->
<!--   Third, explain why null tests are stupid (why are they?). -->
<p>Models have parameters. In Chapter <a href="one-parameter.html#one-parameter">6</a> we created models with a single parameter <span class="math inline">\(p\)</span>, the proportion of red beads in an urn. In Chapter <a href="two-parameters.html#two-parameters">7</a> , we used models with two parameters: <span class="math inline">\(\mu\)</span> (the average height in the population, generically known as a model “intercept”) and <span class="math inline">\(\sigma\)</span> (the variation in height in the population). Here — can you guess where this is going? — we will build models with three parameters: <span class="math inline">\(\sigma\)</span> (which serves the same role throughout the book) and two intercepts: <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span>. All this notation is confusing, not least because different academic fields use inconsistent schemes. The key is to just follow the cardinal virtues and tackle your problem step by step.</p>
<div id="eda-for-trains" class="section level2">
<h2>
<span class="header-section-number">8.1</span> EDA for <code>trains</code>
</h2>
<!-- DK: Still need to standardize the method we use for providing references. -->
<!-- DK: Fix Enos reference. -->
<p>As always, it makes sense to start with some exploratory data analysis (EDA). To demonstrate modeling with three parameters, we will use the <code>trains</code> data set from the <strong>PPBDS.data</strong> package. Recall the discussion from Chapter <a href="rubin-causal-model.html#rubin-causal-model">3</a>. Enos (2014) randomly placed Spanish-speaking confederates on nine train platforms around Boston, Massachusetts. Exposure to Spanish-speakers – the <code>treatment</code> – influenced attitudes toward immigration. These reactions were measured through changes in answers to three survey questions. Let’s load the libraries we will need in this chapter, all of which we have used before, and look at the data.</p>
<div class="sourceCode" id="cb900"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb900-1"><a href="three-parameters.html#cb900-1"></a><span class="kw">library</span>(PPBDS.data)</span>
<span id="cb900-2"><a href="three-parameters.html#cb900-2"></a><span class="kw">library</span>(rstanarm)</span>
<span id="cb900-3"><a href="three-parameters.html#cb900-3"></a><span class="kw">library</span>(broom.mixed)</span>
<span id="cb900-4"><a href="three-parameters.html#cb900-4"></a><span class="kw">library</span>(skimr)</span>
<span id="cb900-5"><a href="three-parameters.html#cb900-5"></a><span class="kw">library</span>(tidyverse)</span></code></pre></div>
<div class="sourceCode" id="cb901"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb901-1"><a href="three-parameters.html#cb901-1"></a><span class="kw">glimpse</span>(trains)</span></code></pre></div>
<pre><code>## Rows: 115
## Columns: 8
## $ gender    &lt;chr&gt; "Female", "Female", "Male", "Male", "Male", "Female", "Fema…
## $ liberal   &lt;lgl&gt; FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE…
## $ party     &lt;chr&gt; "Democrat", "Republican", "Democrat", "Democrat", "Democrat…
## $ age       &lt;dbl&gt; 31, 34, 63, 45, 55, 37, 53, 36, 54, 42, 33, 50, 24, 40, 53,…
## $ income    &lt;dbl&gt; 135000, 105000, 135000, 300000, 135000, 87500, 87500, 13500…
## $ att_start &lt;dbl&gt; 11, 9, 3, 11, 8, 13, 13, 10, 12, 9, 10, 11, 13, 6, 8, 13, 7…
## $ treatment &lt;fct&gt; Treated, Treated, Treated, Treated, Control, Treated, Contr…
## $ att_end   &lt;dbl&gt; 11, 10, 5, 11, 5, 13, 13, 11, 12, 10, 9, 9, 13, 7, 8, 13, 8…</code></pre>
<p>Here, we can see variables that indicate each respondent’s gender, political affiliations, age, and income. Additionally, we have variables that indicate whether a subject was in the control or treatment group, and their attitudes toward immigration both before (<code>att_start</code>) and after (<code>att_end</code>) the experiment. You can type <code>?trains</code> to read the help page for more information about each variable. Let’s restrict attention to a subset of the variables.</p>
<div class="sourceCode" id="cb903"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb903-1"><a href="three-parameters.html#cb903-1"></a>ch8 &lt;-<span class="st"> </span>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb903-2"><a href="three-parameters.html#cb903-2"></a><span class="st">  </span><span class="kw">select</span>(age, att_end, party, treatment)</span></code></pre></div>
<p>It is always smart to look at a some random samples of the data:</p>
<div class="sourceCode" id="cb904"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb904-1"><a href="three-parameters.html#cb904-1"></a>ch8 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb904-2"><a href="three-parameters.html#cb904-2"></a><span class="st">  </span><span class="kw">sample_n</span>(<span class="dv">5</span>)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 4
##     age att_end party      treatment
##   &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;fct&gt;    
## 1    44       9 Democrat   Control  
## 2    67       9 Democrat   Control  
## 3    42      10 Democrat   Treated  
## 4    52      10 Republican Treated  
## 5    46      12 Democrat   Control</code></pre>
<p><code>att_end</code> is a measure of person’s attitude toward immigration, a higher number means more conservative, i.e., a more exclusionary stance on immigration into the United States. Running <code>glimpse()</code> is another way of exploring a data set.</p>
<div class="sourceCode" id="cb906"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb906-1"><a href="three-parameters.html#cb906-1"></a>ch8 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb906-2"><a href="three-parameters.html#cb906-2"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 115
## Columns: 4
## $ age       &lt;dbl&gt; 31, 34, 63, 45, 55, 37, 53, 36, 54, 42, 33, 50, 24, 40, 53,…
## $ att_end   &lt;dbl&gt; 11, 10, 5, 11, 5, 13, 13, 11, 12, 10, 9, 9, 13, 7, 8, 13, 8…
## $ party     &lt;chr&gt; "Democrat", "Republican", "Democrat", "Democrat", "Democrat…
## $ treatment &lt;fct&gt; Treated, Treated, Treated, Treated, Control, Treated, Contr…</code></pre>
<p>Pay attention to the variable types. Do they make sense? Perhaps. But there are certainly grounds for suspicion. Why are <code>age</code> and <code>att_end</code> doubles rather than integers? All the values in the data appear to be integers, so there is no benefit is having these variables be doubles. Why is <code>party</code> a character variable and <code>treatment</code> a factor variable? It could be that these are intentional choices made by the creator of the tibble, i.e., us. These could be mistakes. Or, most likely, these choices are a mixture of sensible and arbitrary. Regardless, it is your responsibility to notice them. You can’t make a good model without looking closely at the data which you are using.</p>
<p><code>skim</code> from the <strong>skimr</strong> package is the best way to get an overview of a tibble.</p>
<div class="sourceCode" id="cb908"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb908-1"><a href="three-parameters.html#cb908-1"></a>ch8 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb908-2"><a href="three-parameters.html#cb908-2"></a><span class="st">  </span><span class="kw">skim</span>()</span></code></pre></div>
<p><!--
<caption>--><span class="marginnote shownote"><span id="tab:unnamed-chunk-701">TABLE 8.1: </span>Data summary</span><!--</caption>--></p>
<table><tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">Piped data</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">115</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">4</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">factor</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">2</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody></table>
<p><strong>Variable type: character</strong></p>
<table>
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">party</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">8</td>
<td align="right">10</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr></tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table>
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="left">ordered</th>
<th align="right">n_unique</th>
<th align="left">top_counts</th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">treatment</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">FALSE</td>
<td align="right">2</td>
<td align="left">Con: 64, Tre: 51</td>
</tr></tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">42.4</td>
<td align="right">12.2</td>
<td align="right">20</td>
<td align="right">33</td>
<td align="right">43</td>
<td align="right">52</td>
<td align="right">68</td>
<td align="left">▆▇▇▇▃</td>
</tr>
<tr class="even">
<td align="left">att_end</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">9.1</td>
<td align="right">2.9</td>
<td align="right">3</td>
<td align="right">7</td>
<td align="right">9</td>
<td align="right">11</td>
<td align="right">15</td>
<td align="left">▂▃▇▃▃</td>
</tr>
</tbody>
</table>
<p><code>skim()</code> shows us what the different values of <code>treatment</code> are because it is a factor. Unfortunately, it does not do the same for character variables like <code>party</code>. The ranges for <code>age</code> and <code>att_end</code> seem reasonable. Recall that participants were asked three questions about immigration issues, each of which allowed for an answer indicated strength of agreement on a scale form 1 to 5, with higher values indicating more agreement with conservative viewpoints. <code>att_end</code> is the sum of the responses to the three questions, so the most liberal possible value is 3 and the most conservative is 15.</p>
<p>Always plot your data.</p>
<div class="sourceCode" id="cb909"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb909-1"><a href="three-parameters.html#cb909-1"></a>ch8 <span class="op">%&gt;%</span></span>
<span id="cb909-2"><a href="three-parameters.html#cb909-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> party, <span class="dt">y =</span> age)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb909-3"><a href="three-parameters.html#cb909-3"></a><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">width =</span> <span class="fl">0.1</span>, <span class="dt">height =</span> <span class="dv">0</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb909-4"><a href="three-parameters.html#cb909-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">"Age by Party Affiliation in Trains Dataset"</span>,</span>
<span id="cb909-5"><a href="three-parameters.html#cb909-5"></a>       <span class="dt">subtitle =</span> <span class="st">"Where are the old Republicans?"</span>,</span>
<span id="cb909-6"><a href="three-parameters.html#cb909-6"></a>       <span class="dt">x =</span> <span class="st">"Party"</span>,</span>
<span id="cb909-7"><a href="three-parameters.html#cb909-7"></a>       <span class="dt">y =</span> <span class="st">"Age"</span>)</span></code></pre></div>
<p><img src="book_temp_files/figure-html/unnamed-chunk-702-1.png" width="672"></p>
<p>From this plot, we can gather that there are many more Democrats in this dataset than Republicans. Democrats also span a wider range of ages than Republicans. The mode age for Democrats appears to be 50.</p>
<div class="sourceCode" id="cb910"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb910-1"><a href="three-parameters.html#cb910-1"></a>ch8 <span class="op">%&gt;%</span></span>
<span id="cb910-2"><a href="three-parameters.html#cb910-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> treatment, <span class="dt">y =</span> att_end)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb910-3"><a href="three-parameters.html#cb910-3"></a><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb910-4"><a href="three-parameters.html#cb910-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">"Attitude End by Treatment in Trains Dataset"</span>,</span>
<span id="cb910-5"><a href="three-parameters.html#cb910-5"></a>       <span class="dt">subtitle =</span> <span class="st">"Did the treatment make people more conservative?"</span>,</span>
<span id="cb910-6"><a href="three-parameters.html#cb910-6"></a>       <span class="dt">x =</span> <span class="st">"Treatment"</span>,</span>
<span id="cb910-7"><a href="three-parameters.html#cb910-7"></a>       <span class="dt">y =</span> <span class="st">"Attitude After Experiment"</span>)</span></code></pre></div>
<p><img src="book_temp_files/figure-html/unnamed-chunk-703-1.png" width="672"></p>
<p>On a boxplot, the top and bottom borders of the box denotes the 75th and 25th percentiles, respectively. The line inside the box denotes the mean of the data. Treated individuals have a higher mean <code>att_end</code> than the control group, and a higher distribution in general, with its 25th percentile lining up with the mean of the control group. The control group has one outlier, while the treatment group has none.</p>
</div>
<div id="age-as-a-function-of-party" class="section level2">
<h2>
<span class="header-section-number">8.2</span> <code>age</code> as a function of <code>party</code>
</h2>
<p>We want to build a model and then use that model to draw conclusions about the world. What is the probability that, if a Democrat shows up at the train station, he will be over 50 years old? In a group of three Democrats and three Republicans, what age difference should we expect between the oldest Democrat and the youngest Republican? We can answer these and similar questions by creating a model that uses party affiliation to predict age</p>
<div id="wisdom" class="section level3">
<h3>
<span class="header-section-number">8.2.1</span> Wisdom</h3>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:unnamed-chunk-704"></span>
<img src="other/images/Wisdom.jpg" alt="Wisdom" width="1280"><!--
<p class="caption marginnote">-->FIGURE 8.1: Wisdom<!--</p>-->
<!--</div>--></span>
</p>
<p>In data science, there are two main aspects to Wisdom: representativeness and ethics. The data that we have are very limited. There are only 115 observations, all from 2012 and involving train commuters to Boston. How useful will this data be today, or for other populations around Boston, or for other cities in the US? Only your judgment, along with advice from your colleagues, can guide you.</p>
<p>The ethical issues are, fortunately, not fraught. Estimating someone’s age is (universally?) viewed as OK. Estimating someone’s health or income or criminal record are far dicier.</p>
</div>
<div id="justice" class="section level3">
<h3>
<span class="header-section-number">8.2.2</span> Justice</h3>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:unnamed-chunk-705"></span>
<img src="other/images/Justice.jpg" alt="Justice" width="960"><!--
<p class="caption marginnote">-->FIGURE 8.2: Justice<!--</p>-->
<!--</div>--></span>
</p>
<p>Justice, in data science, consists of three topics: predictive versus causal modeling, the Preceptor Table and a mathematical formulation of the model.</p>
<p>Any model with age as its dependent variable will be predictive, not causal, for the simple reason that nothing, other than time, can change our age. You are X years old. It would not matter if you changed your party registration from Democrat to Republican or vice versa. Your age is your age.</p>
<p>In terms of the Preceptor Table, this fact means that there is only one potential outcome, i.e., one outcome. There is not a potential outcome if you are Democrat and a different potential outcome if you are a Republican.</p>
<p>When dealing with a non-causal model, the focus is on predicting things. The underlying mechanism which connects age with party is less important than the brute statistical fact that there is a connection. <em>Predictive models care little about causality.</em></p>
<!-- DK: Really need a Preceptor Table! -->
<div id="the-mathematical-model" class="section level4">
<h4>
<span class="header-section-number">8.2.2.1</span> The mathematical model</h4>
<p>We now know that we are working with a predictive model. Recall:</p>
<p><span class="math display">\[outcome = model + not\ in\ the\ model\]</span></p>
<p>In words, any event depends on our explicitly described model as well as on influences unknown to us. Everything that happens in the world is the result of various factors, and we can only ever consider a part of them in our model (because we do not know about some influences, or because we have no data about them).</p>
<p>So far we have only treated the equation above conceptually, but in fact it works just like any other equation. Let’s be a bit more concrete. Our model would formally look like this:</p>
<!-- DK: Should standardize the notation across the book. -->
<p><span class="math display">\[ \underbrace{y_i}_{outcome} = \underbrace{\beta_1 x_{r,i} + \beta_2 x_{d,i}}_{model} + \underbrace{\epsilon_i}_{not\ in\ the\ model}\]</span></p>
<p>where 
<span class="math display">\[x_{r,i}, x_{d,i} \in \{0,1\}\]</span> 
<span class="math display">\[x_{r,i} +  x_{d,i} = 1\]</span> 
<span class="math display">\[\epsilon_i \sim N(0, \sigma^2)\]</span></p>
<p>Don’t panic dear poets and philosophers, the whole thing is easier than it looks at first sight.</p>
<ul>
<li><p>On the left-hand side we have the outcome, <span class="math inline">\(y_i\)</span>, which is the variable to be explained. In our case, this is the age in years of a person.</p></li>
<li><p>On the right-hand side we first have the part contained in the model, consisting of two similar looking terms. The two terms stand for Republicans and Democrats and work as follows. Each term consists of a parameter and a data point. The betas are our two parameters; <span class="math inline">\(\beta_1\)</span> is the average age of Republicans in the population and <span class="math inline">\(\beta_2\)</span> is the average age of Democrats in the population. The x’s are our explanatory variables and take the values 1 or 0. If someone is a Republican we have <span class="math inline">\(x_{r,i} = 1\)</span> and <span class="math inline">\(x_{d,i} = 0\)</span>, if someone is a Democrat we have <span class="math inline">\(x_{r,i} = 0\)</span> and <span class="math inline">\(x_{d,i} = 1\)</span>. In other words, the x’s are binary variables and are mutually exclusive (if you are a Democrat, you cannot also be a Republican).</p></li>
<li><p>The last part, <span class="math inline">\(\epsilon_i\)</span> (“epsilon”), represents the unexplained part and is called the error term. It is simply the difference between the outcome and our model predictions. In our particular case, this includes all factors that have an influence on someone’s age but are not explained by party affiliation. We assume that this error follows a normal distribution with an expected value of 0, i.e., it is 0 on average.</p></li>
<li><p>The small i’s are an index to number observations in our data set. It is equivalent to the “ID” column in our Preceptor Table and simply states that the outcome for person i is explained by the modeled and non-modelled factors for person i. The betas are numbered with 1, 2, 3, etc. The corresponding x’s have an “r” or “d” subscript instead, for Republicans or Democrats.</p></li>
</ul>
</div>
</div>
<div id="courage" class="section level3">
<h3>
<span class="header-section-number">8.2.3</span> Courage</h3>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:unnamed-chunk-706"></span>
<img src="other/images/Courage.jpg" alt="Courage" width="1024"><!--
<p class="caption marginnote">-->FIGURE 8.3: Courage<!--</p>-->
<!--</div>--></span>
</p>
<p>Courage allows us to translate model to code.</p>
<div id="the-fitted-model" class="section level4">
<h4>
<span class="header-section-number">8.2.3.1</span> The fitted model</h4>
<p>To get posterior distributions for our three parameters, we will again use the <code>stan_glm()</code> function from Chapter <a href="two-parameters.html#two-parameters">7</a>. If we take a look at the formula, we can see that it is similar to the equation from before.</p>
<ul>
<li><p>The variable before the tilde, <code>age</code>, is our outcome.</p></li>
<li><p>The only explanatory variable is <code>party</code>. This variable has only two values, ‘Democrat’ and ‘Republican’.</p></li>
<li><p>We have also added <code>- 1</code> at the end of the equation, indicating that we do not want an intercept, which is otherwise added by default. Running this code in R, we get the following output:</p></li>
</ul>
<div class="sourceCode" id="cb911"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb911-1"><a href="three-parameters.html#cb911-1"></a>fit_obj &lt;-<span class="st"> </span><span class="kw">stan_glm</span>(age <span class="op">~</span><span class="st"> </span>party <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> trains, <span class="dt">refresh =</span> <span class="dv">0</span>)</span>
<span id="cb911-2"><a href="three-parameters.html#cb911-2"></a></span>
<span id="cb911-3"><a href="three-parameters.html#cb911-3"></a>fit_obj</span></code></pre></div>
<pre><code>## stan_glm
##  family:       gaussian [identity]
##  formula:      age ~ party - 1
##  observations: 115
##  predictors:   2
## ------
##                 Median MAD_SD
## partyDemocrat   42.6    1.2  
## partyRepublican 41.1    2.8  
## 
## Auxiliary parameter(s):
##       Median MAD_SD
## sigma 12.3    0.8  
## 
## ------
## * For help interpreting the printed output see ?print.stanreg
## * For info on the priors used see ?prior_summary.stanreg</code></pre>
<p>“partyDemocrat” corresponds to <span class="math inline">\(\beta_1\)</span>, the average age of Democrats in the population. “partyRepublican” corresponds to <span class="math inline">\(\beta_2\)</span>, the average age of Republicans in the population. Since we don’t really care about the posterior distribution for <span class="math inline">\(\sigma\)</span>, we won’t discuss it here. Graphically:</p>
<!-- DK: Lots to clean up about this plot! -->
<!-- DK: Should we use different parameter names like beta_r? -->
<div class="sourceCode" id="cb913"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb913-1"><a href="three-parameters.html#cb913-1"></a>fit_obj <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb913-2"><a href="three-parameters.html#cb913-2"></a><span class="st">  </span><span class="kw">as_tibble</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb913-3"><a href="three-parameters.html#cb913-3"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>sigma) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb913-4"><a href="three-parameters.html#cb913-4"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> partyDemocrat<span class="op">:</span>partyRepublican,</span>
<span id="cb913-5"><a href="three-parameters.html#cb913-5"></a>              <span class="dt">names_to =</span> <span class="st">"parameter"</span>,</span>
<span id="cb913-6"><a href="three-parameters.html#cb913-6"></a>              <span class="dt">values_to =</span> <span class="st">"age"</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb913-7"><a href="three-parameters.html#cb913-7"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> age, <span class="dt">color =</span> parameter)) <span class="op">+</span></span>
<span id="cb913-8"><a href="three-parameters.html#cb913-8"></a><span class="st">    </span><span class="kw">geom_density</span>() <span class="op">+</span></span>
<span id="cb913-9"><a href="three-parameters.html#cb913-9"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">"Posterior Probability Distribution"</span>,</span>
<span id="cb913-10"><a href="three-parameters.html#cb913-10"></a>         <span class="dt">subtitle =</span> <span class="st">"Average age for Boston commuters in 2012"</span>,</span>
<span id="cb913-11"><a href="three-parameters.html#cb913-11"></a>         <span class="dt">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb913-12"><a href="three-parameters.html#cb913-12"></a>         <span class="dt">y =</span> <span class="st">"Probability"</span>) <span class="op">+</span></span>
<span id="cb913-13"><a href="three-parameters.html#cb913-13"></a><span class="st">    </span><span class="kw">theme_classic</span>()</span></code></pre></div>
<p><img src="book_temp_files/figure-html/unnamed-chunk-708-1.png" width="672"></p>
<p>The unknown parameters <span class="math inline">\(\beta_1\)</span> (partyDemocrat) and <span class="math inline">\(\beta_2\)</span> (partyRepublican) are still unknown. We can never know the true average age of all Democrats in the population. But we can calculate a posterior probability distribution for the parameters. Comments:</p>
<ul>
<li><p>Democrats seem slightly older than Republicans. That was true in our sample and so, almost (but not quite!) by definition, it will be true in our the posterior probability distributions.</p></li>
<li><p>Our estimate for the average age of Democrats in the population is much more precise than that for Republicans because we have five times as many Democrats as Republicans in our sample. A central lesson from Chapter <a href="#one-paramter"><strong>??</strong></a> is that, the more data you have related to a parameter, the narrower your posterior distribution will be.</p></li>
<li><p>There is a great deal of overlap between the two distributions. Would we be surprised if, in truth, the average age of Republicans in the population was greater than that for Democrats? Not really. We don’t have enough data to be sure either way.</p></li>
<li><p>The phrase “in the population” is doing a great deal of work because we have not what, precisely, we mean by the population. Is it the set of people on those commuter platforms on those days in 2012 when the experiment was done? Is it the set of people on all platforms, including ones never visited? Is it the set of all Boston commuter? All Massachusetts residents? All US residents? Does it include people today, or can we only draw inferences for 2012? We will explore these questions in every model we create.</p></li>
</ul>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#mwpnvhibij .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#mwpnvhibij .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#mwpnvhibij .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#mwpnvhibij .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#mwpnvhibij .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#mwpnvhibij .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#mwpnvhibij .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#mwpnvhibij .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#mwpnvhibij .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#mwpnvhibij .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#mwpnvhibij .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#mwpnvhibij .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#mwpnvhibij .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#mwpnvhibij .gt_from_md > :first-child {
  margin-top: 0;
}

#mwpnvhibij .gt_from_md > :last-child {
  margin-bottom: 0;
}

#mwpnvhibij .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#mwpnvhibij .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#mwpnvhibij .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#mwpnvhibij .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#mwpnvhibij .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#mwpnvhibij .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#mwpnvhibij .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#mwpnvhibij .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#mwpnvhibij .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#mwpnvhibij .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#mwpnvhibij .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#mwpnvhibij .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#mwpnvhibij .gt_left {
  text-align: left;
}

#mwpnvhibij .gt_center {
  text-align: center;
}

#mwpnvhibij .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#mwpnvhibij .gt_font_normal {
  font-weight: normal;
}

#mwpnvhibij .gt_font_bold {
  font-weight: bold;
}

#mwpnvhibij .gt_font_italic {
  font-style: italic;
}

#mwpnvhibij .gt_super {
  font-size: 65%;
}

#mwpnvhibij .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="mwpnvhibij" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="4" class="gt_heading gt_title gt_font_normal" style>8 Observations from Trains Dataset</th>
    </tr>
<tr>
<th colspan="4" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style></th>
    </tr>
</thead>
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Age</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Party</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Fitted</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Residual</strong></th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_center">31</td>
      <td class="gt_row gt_center">Democrat</td>
      <td class="gt_row gt_center">42.61</td>
      <td class="gt_row gt_center">-11.6</td>
    </tr>
<tr>
<td class="gt_row gt_center">34</td>
      <td class="gt_row gt_center">Republican</td>
      <td class="gt_row gt_center">41.13</td>
      <td class="gt_row gt_center">-7.1</td>
    </tr>
<tr>
<td class="gt_row gt_center">63</td>
      <td class="gt_row gt_center">Democrat</td>
      <td class="gt_row gt_center">42.61</td>
      <td class="gt_row gt_center">20.4</td>
    </tr>
<tr>
<td class="gt_row gt_center">45</td>
      <td class="gt_row gt_center">Democrat</td>
      <td class="gt_row gt_center">42.61</td>
      <td class="gt_row gt_center">2.4</td>
    </tr>
<tr>
<td class="gt_row gt_center">55</td>
      <td class="gt_row gt_center">Democrat</td>
      <td class="gt_row gt_center">42.61</td>
      <td class="gt_row gt_center">12.4</td>
    </tr>
<tr>
<td class="gt_row gt_center">37</td>
      <td class="gt_row gt_center">Democrat</td>
      <td class="gt_row gt_center">42.61</td>
      <td class="gt_row gt_center">-5.6</td>
    </tr>
<tr>
<td class="gt_row gt_center">53</td>
      <td class="gt_row gt_center">Republican</td>
      <td class="gt_row gt_center">41.13</td>
      <td class="gt_row gt_center">11.9</td>
    </tr>
<tr>
<td class="gt_row gt_center">36</td>
      <td class="gt_row gt_center">Democrat</td>
      <td class="gt_row gt_center">42.61</td>
      <td class="gt_row gt_center">-6.6</td>
    </tr>
</tbody>
</table></div>
<p>The fitted values are the same for all Republicans and for all Democrats, as the fitted value is one of the two estimates output by our model. However, almost all of the residuals are different due to each observation’s own variation from the fitted value estimate. This table shows how just a sample of 8 individuals captures a wide range of residuals, making it difficult to predict the age of a new individual who walks in the room even using our model.</p>
<p>We can get a better picture of the unmodeled variation in our sample if we plot these three values for all individuals in our data set. The following three histograms show the actual outcomes, fitted values and residuals of all people in <code>trains</code>:</p>
<!-- DK: Clean up these plots to be similar across chapters! -->
<p><img src="book_temp_files/figure-html/unnamed-chunk-710-1.png" width="672" style="display: block; margin: auto;"></p>
<p>The three plots are structured like our equation and table above, i.e. a value in the left plot is the addition of one value in the middle and one in the right plot. The actual age distribution looks like a normal distribution, centered around 43 and with a standard deviation of about 12 years. The plot for the fitted values shows only two adjacent spikes, which represent the estimates for Democrats and Republicans. Since the residuals represent the difference between the two plots, their distribution looks like the first plot.</p>
<!-- DK: All unclear and would benefit from clean up. -->
</div>
</div>
<div id="temperance" class="section level3">
<h3>
<span class="header-section-number">8.2.4</span> Temperance</h3>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:unnamed-chunk-711"></span>
<img src="other/images/Temperance.jpg" alt="Temperance" width="960"><!--
<p class="caption marginnote">-->FIGURE 8.4: Temperance<!--</p>-->
<!--</div>--></span>
</p>
<p>Recall the first questions with which we began this section:</p>
<ul>
<li>What is the probability that, if a Democrat shows up at the train station, he will be over 50 years old?</li>
</ul>
<p>So far we have only tried our model on people from our data set whose real age we already knew. This is helpful to understand the model, but our ultimate goal is to understand more about the real world, about people we don’t yet know much about. Temperance guides us to make meaningful predictions and to become aware of their known and unknown limitations.</p>
<div id="making-predictions" class="section level4">
<h4>
<span class="header-section-number">8.2.4.1</span> Making Predictions</h4>
<p>We learned in Chapter <a href="two-parameters.html#two-parameters">7</a> that, when running <code>stan_glm</code>, an algorithm creates thousands of simulations, each of which contains a draw from the posterior distribution of each parameter. .</p>
<p>What sounds complicated is actually just a matter of a few extra lines of code. To start with a simple question, what are the chances that a random Democrat is over 50 years old? First, we create a tibble with the desired input for our model. In our case the tibble has a column named “party” which contains a single observation named “Democrat”. This is a bit different than before, when we only specified the input to be 0 or 1. Next, we’ll use the <code>posterior_predict()</code> function to get some simulation results. <code>posterior_predict()</code> takes two arguments: the model for which the simulations should be run, and a tibble indicating for which and how many parameters we want to run these simulations. In this case, the model is the one from ‘Courage’ and the tibble is the one we just created.</p>
<div class="sourceCode" id="cb914"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb914-1"><a href="three-parameters.html#cb914-1"></a><span class="co"># Creating a tibble with a column named "party" and a single observation,</span></span>
<span id="cb914-2"><a href="three-parameters.html#cb914-2"></a><span class="co"># "Democrat". We will use this to tell posterior_predict() that we want</span></span>
<span id="cb914-3"><a href="three-parameters.html#cb914-3"></a><span class="co"># simulation results for a single Democrat.</span></span>
<span id="cb914-4"><a href="three-parameters.html#cb914-4"></a></span>
<span id="cb914-5"><a href="three-parameters.html#cb914-5"></a>new &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">party =</span> <span class="st">"Democrat"</span>)</span>
<span id="cb914-6"><a href="three-parameters.html#cb914-6"></a></span>
<span id="cb914-7"><a href="three-parameters.html#cb914-7"></a><span class="co"># Generating simulation results. The first argument specifies the fitted model</span></span>
<span id="cb914-8"><a href="three-parameters.html#cb914-8"></a><span class="co"># to be used, which in our case is the one we generated in "Courage". The second</span></span>
<span id="cb914-9"><a href="three-parameters.html#cb914-9"></a><span class="co"># argument specifies the input.</span></span>
<span id="cb914-10"><a href="three-parameters.html#cb914-10"></a></span>
<span id="cb914-11"><a href="three-parameters.html#cb914-11"></a>pp &lt;-<span class="st"> </span><span class="kw">posterior_predict</span>(fit_obj, <span class="dt">newdata =</span> new)</span>
<span id="cb914-12"><a href="three-parameters.html#cb914-12"></a></span>
<span id="cb914-13"><a href="three-parameters.html#cb914-13"></a><span class="kw">head</span>(pp, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##        1
##  [1,] 17
##  [2,] 38
##  [3,] 38
##  [4,] 14
##  [5,] 49
##  [6,] 61
##  [7,] 36
##  [8,] 29
##  [9,] 64
## [10,] 51</code></pre>
<p>A look at the first few observations shows that we simply get ten draws from the model’s posterior distribution of the age of a Democrat. It is important to understand that this is not a concrete person from the <code>trains</code> dataset - the algorithm in <code>posterior_predict()</code> simply uses the existing data from <code>trains</code> to estimate this posterior distribution.</p>
<p>Note that we have a new posterior distribution under consideration here. The unknown parameter, call it <span class="math inline">\(D_{age}\)</span> is the age of a Democrat. This could be the age of a randomly selected Democrat from the population or of the next Democrat we meet or of the next Democrat we interview on the train platform. The definition of “population” determines the appropriate interpretation. Yet, regardless, <span class="math inline">\(D_{age}\)</span> is an unknown parameter, not one, like <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\beta_2\)</span>, or <span class="math inline">\(\sigma\)</span> that we have already estimated. That is why we need <code>posterior_predict()</code>.</p>
<div class="sourceCode" id="cb916"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb916-1"><a href="three-parameters.html#cb916-1"></a><span class="kw">tibble</span>(<span class="dt">age =</span> pp[, <span class="dv">1</span>]) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb916-2"><a href="three-parameters.html#cb916-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> age)) <span class="op">+</span></span>
<span id="cb916-3"><a href="three-parameters.html#cb916-3"></a><span class="st">    </span><span class="kw">geom_density</span>() <span class="op">+</span></span>
<span id="cb916-4"><a href="three-parameters.html#cb916-4"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">"Posterior Probability Distribution for a Democrat's Age"</span>,</span>
<span id="cb916-5"><a href="three-parameters.html#cb916-5"></a>         <span class="dt">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb916-6"><a href="three-parameters.html#cb916-6"></a>         <span class="dt">y =</span> <span class="st">"Probability"</span>) <span class="op">+</span></span>
<span id="cb916-7"><a href="three-parameters.html#cb916-7"></a><span class="st">    </span><span class="kw">theme_linedraw</span>()</span></code></pre></div>
<p><img src="book_temp_files/figure-html/unnamed-chunk-713-1.png" width="672"></p>
<p>Once we have the posterior distribution, we can answer (almost) any reasonable question. In this case, the probability that the next Democrat will be over 50 is around 28%.</p>
<div class="sourceCode" id="cb917"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb917-1"><a href="three-parameters.html#cb917-1"></a><span class="kw">tibble</span>(<span class="dt">age =</span> pp[, <span class="dv">1</span>]) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb917-2"><a href="three-parameters.html#cb917-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ot_50 =</span> <span class="kw">ifelse</span>(age <span class="op">&gt;</span><span class="st"> </span><span class="dv">50</span>, <span class="ot">TRUE</span>, <span class="ot">FALSE</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb917-3"><a href="three-parameters.html#cb917-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">perc =</span> <span class="kw">sum</span>(ot_<span class="dv">50</span>)<span class="op">/</span><span class="kw">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##    perc
##   &lt;dbl&gt;
## 1 0.266</code></pre>
<p>Recall the second question:</p>
<ul>
<li>In a group of three Democrats and three Republicans, what age difference should we expect between the oldest Democrat and the youngest Republican?</li>
</ul>
<p>As before we start by creating a tibble with the desired input. Note that the name of the column (“party”) and the observations (“Democrat”, “Republican”) must always be <em>exactly</em> as they the data set. This tibble as well as our model can then be used as arguments for <code>posterior_predict()</code>:</p>
<div class="sourceCode" id="cb919"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb919-1"><a href="three-parameters.html#cb919-1"></a>new &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">party =</span> <span class="kw">c</span>(<span class="st">"Democrat"</span>, <span class="st">"Democrat"</span>, <span class="st">"Democrat"</span>, </span>
<span id="cb919-2"><a href="three-parameters.html#cb919-2"></a>                        <span class="st">"Republican"</span>, <span class="st">"Republican"</span>,<span class="st">"Republican"</span>))</span>
<span id="cb919-3"><a href="three-parameters.html#cb919-3"></a></span>
<span id="cb919-4"><a href="three-parameters.html#cb919-4"></a>pp &lt;-<span class="st"> </span><span class="kw">posterior_predict</span>(fit_obj, <span class="dt">newdata =</span> new)</span>
<span id="cb919-5"><a href="three-parameters.html#cb919-5"></a></span>
<span id="cb919-6"><a href="three-parameters.html#cb919-6"></a><span class="kw">head</span>(pp, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##        1  2  3  4  5  6
##  [1,] 45 50 53 57 23 58
##  [2,] 43 50 57 34 34 40
##  [3,] 48 42 28 34 31 39
##  [4,] 40 35 35 37 18 59
##  [5,] 72 41 37 70 36 23
##  [6,] 53 55 55 19 34 24
##  [7,] 39 31 57 31 60 47
##  [8,] 50 38 72 50 23 78
##  [9,] 72 28 40 40 66 17
## [10,] 37 45 40 53 52 40</code></pre>
<p>A look at the output shows that we now have 6 columns: one for each person. R does not name the columns, but they are arranged in the same order in which we specified the persons in the tibble (D, D, R, R, R). Notice that all values in a row belong to the same scenario, i.e. each row represents a scenario where the 6 people meet.</p>
<p>To determine the expected age difference, we can then proceed as follows:</p>
<div class="sourceCode" id="cb921"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb921-1"><a href="three-parameters.html#cb921-1"></a><span class="kw">as_tibble</span>(pp) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb921-2"><a href="three-parameters.html#cb921-2"></a><span class="st">  </span><span class="kw">set_names</span>(<span class="kw">c</span>(<span class="st">"dem_1"</span>, <span class="st">"dem_2"</span>, <span class="st">"dem_3"</span>, </span>
<span id="cb921-3"><a href="three-parameters.html#cb921-3"></a>              <span class="st">"rep_1"</span>, <span class="st">"rep_2"</span>, <span class="st">"rep_3"</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb921-4"><a href="three-parameters.html#cb921-4"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb921-5"><a href="three-parameters.html#cb921-5"></a><span class="st">  </span></span>
<span id="cb921-6"><a href="three-parameters.html#cb921-6"></a><span class="st">  </span><span class="co"># Creating three new columns. The first two are the </span></span>
<span id="cb921-7"><a href="three-parameters.html#cb921-7"></a><span class="st">  </span><span class="co"># highest age among Democrats and the lowest age</span></span>
<span id="cb921-8"><a href="three-parameters.html#cb921-8"></a><span class="st">  </span><span class="co"># among Republicans, respectively. The third one is</span></span>
<span id="cb921-9"><a href="three-parameters.html#cb921-9"></a><span class="st">  </span><span class="co"># the difference between the first two.</span></span>
<span id="cb921-10"><a href="three-parameters.html#cb921-10"></a><span class="st">  </span></span>
<span id="cb921-11"><a href="three-parameters.html#cb921-11"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">dems_oldest =</span> <span class="kw">max</span>(<span class="kw">c</span>(dem_<span class="dv">1</span>, dem_<span class="dv">2</span>, dem_<span class="dv">3</span>)),</span>
<span id="cb921-12"><a href="three-parameters.html#cb921-12"></a>         <span class="dt">reps_youngest =</span> <span class="kw">min</span>(<span class="kw">c</span>(rep_<span class="dv">1</span>, rep_<span class="dv">2</span>, rep_<span class="dv">3</span>)),</span>
<span id="cb921-13"><a href="three-parameters.html#cb921-13"></a>         <span class="dt">age_diff =</span> dems_oldest <span class="op">-</span><span class="st"> </span>reps_youngest) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb921-14"><a href="three-parameters.html#cb921-14"></a><span class="st">  </span></span>
<span id="cb921-15"><a href="three-parameters.html#cb921-15"></a><span class="st">  </span><span class="co"># Ungroup to tell R not to perform rowwise operations</span></span>
<span id="cb921-16"><a href="three-parameters.html#cb921-16"></a><span class="st">  </span><span class="co"># anymore.</span></span>
<span id="cb921-17"><a href="three-parameters.html#cb921-17"></a><span class="st">  </span></span>
<span id="cb921-18"><a href="three-parameters.html#cb921-18"></a><span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb921-19"><a href="three-parameters.html#cb921-19"></a><span class="st">  </span></span>
<span id="cb921-20"><a href="three-parameters.html#cb921-20"></a><span class="st">  </span><span class="co"># Create posterior probability distribution</span></span>
<span id="cb921-21"><a href="three-parameters.html#cb921-21"></a><span class="st">  </span></span>
<span id="cb921-22"><a href="three-parameters.html#cb921-22"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> age_diff)) <span class="op">+</span></span>
<span id="cb921-23"><a href="three-parameters.html#cb921-23"></a><span class="st">    </span><span class="kw">geom_density</span>() <span class="op">+</span></span>
<span id="cb921-24"><a href="three-parameters.html#cb921-24"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">"Posterior Probability Distribution"</span>,</span>
<span id="cb921-25"><a href="three-parameters.html#cb921-25"></a>         <span class="dt">subtitle =</span> <span class="st">"Age difference between the oldest/youngest of three Democrats/Republicans"</span>,</span>
<span id="cb921-26"><a href="three-parameters.html#cb921-26"></a>         <span class="dt">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb921-27"><a href="three-parameters.html#cb921-27"></a>         <span class="dt">y =</span> <span class="st">"Probability"</span>)</span></code></pre></div>
<p><img src="book_temp_files/figure-html/unnamed-chunk-716-1.png" width="672"></p>
<p>In words, we would expect the oldest Democrat to be about 22 years older than the youngest Republican, but we would not be surprised if the oldest Democrat were actually younger than the youngest Republican.</p>
</div>
</div>
</div>
<div id="att_end-as-a-function-of-treatment" class="section level2">
<h2>
<span class="header-section-number">8.3</span> <code>att_end</code> as a function of <code>treatment</code>
</h2>
<p>Above, we created a predictive model: with someone’s party affiliation, we can make a better guess as to what their age is. There was nothing causal about that model. Changing someone’s party registration can not change their age. In this example, we build a causal model. What is the effect of exposing someone on a train platform to Spanish-speakers on their attitudes toward immigration?</p>
<div id="wisdom-1" class="section level3">
<h3>
<span class="header-section-number">8.3.1</span> Wisdom</h3>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:unnamed-chunk-717"></span>
<img src="other/images/Wisdom.jpg" alt="Wisdom" width="1280"><!--
<p class="caption marginnote">-->FIGURE 8.5: Wisdom<!--</p>-->
<!--</div>--></span>
</p>
</div>
<div id="justice-1" class="section level3">
<h3>
<span class="header-section-number">8.3.2</span> Justice</h3>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:unnamed-chunk-718"></span>
<img src="other/images/Justice.jpg" alt="Justice" width="960"><!--
<p class="caption marginnote">-->FIGURE 8.6: Justice<!--</p>-->
<!--</div>--></span>
</p>
</div>
<div id="courage-1" class="section level3">
<h3>
<span class="header-section-number">8.3.3</span> Courage</h3>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:unnamed-chunk-719"></span>
<img src="other/images/Courage.jpg" alt="Courage" width="1024"><!--
<p class="caption marginnote">-->FIGURE 8.7: Courage<!--</p>-->
<!--</div>--></span>
</p>
<div class="sourceCode" id="cb922"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb922-1"><a href="three-parameters.html#cb922-1"></a>obj &lt;-<span class="st"> </span><span class="kw">stan_glm</span>(att_end <span class="op">~</span><span class="st"> </span>treatment <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> trains, <span class="dt">refresh =</span> <span class="dv">0</span>)</span>
<span id="cb922-2"><a href="three-parameters.html#cb922-2"></a></span>
<span id="cb922-3"><a href="three-parameters.html#cb922-3"></a>obj</span></code></pre></div>
<pre><code>## stan_glm
##  family:       gaussian [identity]
##  formula:      att_end ~ treatment - 1
##  observations: 115
##  predictors:   2
## ------
##                  Median MAD_SD
## treatmentTreated 10.0    0.4  
## treatmentControl  8.4    0.4  
## 
## Auxiliary parameter(s):
##       Median MAD_SD
## sigma 2.8    0.2   
## 
## ------
## * For help interpreting the printed output see ?print.stanreg
## * For info on the priors used see ?prior_summary.stanreg</code></pre>
<p>Note that for both Democrats and Republicans, the prediction interval is significantly wider than the confidence interval. This discrepancy illustrates the <em>unmodeled variation</em> of the dataset: while the mean values, as indicated by the “fit” column, are still the best guess you can make for any given subject, we are less confident in the value range of that individual subject than we are of the value range of the mean. <em>The unmodeled variation widens the prediction intervals relative to the confidence intervals.</em></p>
<p>Recall our discussion regarding the wider confidence intervals for Republican subjects than Democrat subjects. Although the Republican and Democrat average incomes had vastly different confidence intervals — the Republican confidence intervals were much wider — they have very similar prediction intervals. Although the <em>parameter uncertainty</em> of these two parameters were very different, the <em>unmodeled variation</em> for both parameters was roughly the same. Even though the data points were equally spread out for both Democrat and Republican income, were were able to more confidently pinpoint a true value for democrat income because we had more data to work with.</p>
<p>In many cases, the most important use of a model is for prediction. We use them to make predictions about data which we have not yet seen.</p>
<p>And we can reconstruct the table by filling in the unknowns with the predictions (note that these are unchanged) and their associated levels of uncertainty (which HAVE changed to accommodate for individual variation within the data):</p>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#xtguwrzspl .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#xtguwrzspl .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xtguwrzspl .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#xtguwrzspl .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#xtguwrzspl .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xtguwrzspl .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xtguwrzspl .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#xtguwrzspl .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#xtguwrzspl .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#xtguwrzspl .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#xtguwrzspl .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#xtguwrzspl .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#xtguwrzspl .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#xtguwrzspl .gt_from_md > :first-child {
  margin-top: 0;
}

#xtguwrzspl .gt_from_md > :last-child {
  margin-bottom: 0;
}

#xtguwrzspl .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#xtguwrzspl .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#xtguwrzspl .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xtguwrzspl .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#xtguwrzspl .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xtguwrzspl .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#xtguwrzspl .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#xtguwrzspl .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xtguwrzspl .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xtguwrzspl .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#xtguwrzspl .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xtguwrzspl .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#xtguwrzspl .gt_left {
  text-align: left;
}

#xtguwrzspl .gt_center {
  text-align: center;
}

#xtguwrzspl .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#xtguwrzspl .gt_font_normal {
  font-weight: normal;
}

#xtguwrzspl .gt_font_bold {
  font-weight: bold;
}

#xtguwrzspl .gt_font_italic {
  font-style: italic;
}

#xtguwrzspl .gt_super {
  font-size: 65%;
}

#xtguwrzspl .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="xtguwrzspl" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="3" class="gt_heading gt_title gt_font_normal" style>Ending Attitudes on Immigration of 7 Random Respondents</th>
    </tr>
<tr>
<th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style></th>
    </tr>
</thead>
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Subject</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$Y_c(u)$$</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$Y_t(u)$$</strong></th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">7</td>
      <td class="gt_row gt_center">8.45 (2.9-14.0)</td>
      <td class="gt_row gt_center">11</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">6,041</td>
      <td class="gt_row gt_center">8.45 (2.9-14.0)</td>
      <td class="gt_row gt_center">10</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">67</td>
      <td class="gt_row gt_center">8.45 (2.9-14.0)</td>
      <td class="gt_row gt_center">5</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">40,080</td>
      <td class="gt_row gt_center">8.45 (2.9-14.0)</td>
      <td class="gt_row gt_center">11</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">758</td>
      <td class="gt_row gt_center">5</td>
      <td class="gt_row gt_center">10 (4.4-15.6)</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">32</td>
      <td class="gt_row gt_center">8.45 (2.9-14.0)</td>
      <td class="gt_row gt_center">13</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">8,809</td>
      <td class="gt_row gt_center">13</td>
      <td class="gt_row gt_center">10 (4.4-15.6)</td>
    </tr>
</tbody>
</table></div>
</div>
<div id="temperance-1" class="section level3">
<h3>
<span class="header-section-number">8.3.4</span> Temperance</h3>
<p>
<span class="marginnote shownote">
<!--
<div class="figure">--><span id="fig:unnamed-chunk-722"></span>
<img src="other/images/Temperance.jpg" alt="Temperance" width="960"><!--
<p class="caption marginnote">-->FIGURE 8.8: Temperance<!--</p>-->
<!--</div>--></span>
</p>
<p>There are various sources of uncertainties and problems that have addressed in previous chapters and again in this chapter. It’s important that you always have these in the back of your mind when working with data:</p>
<ol style="list-style-type: decimal">
<li><p><em>Validity</em>. At the surface level, parameter names might not invoke too much thought — but once you really sit down and think about the story the numbers are trying to tell, it’s not always the case that the numbers deserve to tell that story. In our earlier discussion regarding <code>income</code> and <code>att_end</code>, the conclusions we draw from these data might be misleading just because the way they were collected or computed inevitably change these conclusions. Even when there’s nothing WRONG with a setup, we need to keep in mind that the smallest differences</p></li>
<li><p>When we dive deeper into the data, we run into the issue of <em>parameter uncertainty</em>, which is the uncertainty associated with our analysis of summary parameters, such as mean, median, and range. In our above analysis with the <code>trains</code> dataset, we account for parameter uncertainty using confidence intervals.</p></li>
<li><p>As great as confidence intervals are, they don’t capture the uncertainty of using summary statistics to predict parameter values of random individuals. We are more sure, for example, about the range of possible incomes for the mean income of American democrats than we are about the range of possible incomes for a single American democrat, whose income could stray far from the mean democrat income. This <em>unmodeled variation</em>, or variation between data points that is not fully captured by bootstrapping, deserves much consideration when dealing with data.</p></li>
<li><p><em>Unknown unknowns</em> are an especially unavoidable source of uncertainty. The world is changing, and people 50 years from now might act differently and have vastly different lifestyles and characteristics; in the case of the <code>trains</code> dataset, it wouldn’t be unreasonable to expect completely different combinations of income and party affiliation. That would render our mean income, median ratio, and prediction intervals for both those measures useless.</p></li>
</ol>
<p>The <em>fitted value</em> of att_end is 8.45 for the control group and 10 for the treated group. Because a higher att_end means more conservative towards stances on immigration, it seems that treated individuals had more conservative stances on this issue than the control group by the end of the study.</p>
</div>
<div id="model-structure" class="section level3">
<h3>
<span class="header-section-number">8.3.5</span> Model Structure</h3>
<p>Our predictive model helped us make guesses as to what an individual’s age is. However, that’s just about all we can do with this relationship. Recall that the trains dataset was originally introduced in the context of the Rubin Causal Model back in Chapter <a href="rubin-causal-model.html#rubin-causal-model">3</a>. That model cannot be applied to the relationship between party and income because these values were independently decided outside the experiment — although we were able to identify correlations between those two variables, the combinations of party and income were predetermined and not randomly assigned in a way that allows us to establish a causal relationship. If an individual suddenly decided to change party affiliations, we wouldn’t suddenly expect his or her income to spike or plummet.</p>
<p>In conclusion, while we can explore correlations or trends between party and income, we cannot label these correlations or trends as causal. However, <code>treatment</code> was a variable that was randomly assigned to subjects, and we have a variable that was measured after this random assignment, <code>att_end</code>. With this setup, we can calculate the Average Treatment Effect, or the average difference in <code>att_end</code> for treated subjects and control subjects.</p>
<div class="sourceCode" id="cb924"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb924-1"><a href="three-parameters.html#cb924-1"></a>mean_ends &lt;-<span class="st"> </span>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb924-2"><a href="three-parameters.html#cb924-2"></a><span class="st">  </span><span class="kw">group_by</span>(treatment) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb924-3"><a href="three-parameters.html#cb924-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_att_end =</span> <span class="kw">mean</span>(att_end))</span></code></pre></div>
<div class="sourceCode" id="cb925"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb925-1"><a href="three-parameters.html#cb925-1"></a>ATE &lt;-<span class="st"> </span>mean_ends<span class="op">$</span>mean_att_end[<span class="dv">2</span>] <span class="op">-</span><span class="st"> </span>mean_ends<span class="op">$</span>mean_att_end[<span class="dv">1</span>]</span></code></pre></div>
<p>Now, let’s make a Preceptor Table for this data:</p>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#grhixuxsvj .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#grhixuxsvj .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#grhixuxsvj .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#grhixuxsvj .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#grhixuxsvj .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#grhixuxsvj .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#grhixuxsvj .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#grhixuxsvj .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#grhixuxsvj .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#grhixuxsvj .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#grhixuxsvj .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#grhixuxsvj .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#grhixuxsvj .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#grhixuxsvj .gt_from_md > :first-child {
  margin-top: 0;
}

#grhixuxsvj .gt_from_md > :last-child {
  margin-bottom: 0;
}

#grhixuxsvj .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#grhixuxsvj .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#grhixuxsvj .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#grhixuxsvj .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#grhixuxsvj .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#grhixuxsvj .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#grhixuxsvj .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#grhixuxsvj .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#grhixuxsvj .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#grhixuxsvj .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#grhixuxsvj .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#grhixuxsvj .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#grhixuxsvj .gt_left {
  text-align: left;
}

#grhixuxsvj .gt_center {
  text-align: center;
}

#grhixuxsvj .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#grhixuxsvj .gt_font_normal {
  font-weight: normal;
}

#grhixuxsvj .gt_font_bold {
  font-weight: bold;
}

#grhixuxsvj .gt_font_italic {
  font-style: italic;
}

#grhixuxsvj .gt_super {
  font-size: 65%;
}

#grhixuxsvj .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="grhixuxsvj" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="3" class="gt_heading gt_title gt_font_normal" style>Preceptor Table of att_end ~ treatment</th>
    </tr>
<tr>
<th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style></th>
    </tr>
</thead>
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>ID</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>treatment</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>att_end</strong></th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>1</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>treated</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>11</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>2</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>75</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>control</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>5</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>564</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>control</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>13</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>565</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>10,627</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>treated</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>11</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>N</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
    </tr>
</tbody>
</table></div>
<p>Preceptor Tables aim to capture all of the data such that if the question marks were filled out, one wouldn’t need to construct a model. The rows in this Preceptor Table represent the N commuters on which our model is extrapolating, with N being the population of commuters using Boston public transportation. However, we’re going to need a different kind of table if we want to display the causal effect of being treated – more with this soon.</p>
<p>Next, the second part of model structure, the formula.</p>
<p><span class="math display">\[ y_i = b_1 x_t + b_2 x_c\]</span>
Once again, we start here. We can make our parameters constants, <span class="math inline">\(\hat{b_1}\)</span> and <span class="math inline">\(\hat{b_1}\)</span>, by assigning them to the estimates of the model. Plugging in these numbers outputs an estimated att_end for the observation, or our <em>fitted value</em> <span class="math inline">\(\hat{y_i}\)</span>.</p>
<p><span class="math display">\[ \hat{y_i} = \hat{b_1} x_t + \hat{b_2} x_c  \]</span>
<span class="math display">\[ \hat{y_i} = 8.45x_t + 10x_c \]</span>
When the individual is treated (<span class="math inline">\(x_t\)</span>=1 and <span class="math inline">\(x_c\)</span>=0), their fitted value is 8.45. When the individual is a control (<span class="math inline">\(x_t\)</span>=0 and <span class="math inline">\(x_c\)</span>=1), their fiited value is 42.6.</p>
<p>Subtract the recorded att_end by fitted value for the epsilon value…
<span class="math display">\[\epsilon_i = y_i - \hat{y_i}\]</span>
…And you can now complete your equation.
<span class="math display">\[ y_i = \hat{b_1}x_r + \hat{b_2} x_d + \epsilon_i \]</span>
Note that the math for both the predictive model we worked on earlier and this model is <em>identical</em>. It is not the calculations for the residual, fitted value, or parameter estimates that differ between these two model types; rather, it is how one uses and interprets these numbers. While predictive models are simply used for predicting another variable’s value (in the previous case, age), we can use these numbers to calculate the effect of one variable (treatment) on another (att_end) for each individual observation.</p>
<p>Now, we’ll create a Rubin Causal Model table of possible outcomes, as we did back in ch3. We’ll do this using 7 random observations from the trains dataset.</p>
<div class="sourceCode" id="cb926"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb926-1"><a href="three-parameters.html#cb926-1"></a><span class="co">#Adding question marks where necessary</span></span>
<span id="cb926-2"><a href="three-parameters.html#cb926-2"></a></span>
<span id="cb926-3"><a href="three-parameters.html#cb926-3"></a>trains_RCM &lt;-<span class="st"> </span>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb926-4"><a href="three-parameters.html#cb926-4"></a><span class="st">  </span><span class="kw">pivot_wider</span>(<span class="dt">names_from =</span> treatment, <span class="dt">values_from =</span> att_end) <span class="op">%&gt;%</span></span>
<span id="cb926-5"><a href="three-parameters.html#cb926-5"></a><span class="st">  </span><span class="kw">slice</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">7</span>) <span class="op">%&gt;%</span></span>
<span id="cb926-6"><a href="three-parameters.html#cb926-6"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">subject =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">7</span>) <span class="op">%&gt;%</span></span>
<span id="cb926-7"><a href="three-parameters.html#cb926-7"></a><span class="st">  </span><span class="kw">replace_na</span>(<span class="kw">list</span>(<span class="dt">Treated =</span> <span class="st">"?"</span>, <span class="dt">Control =</span> <span class="st">"?"</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb926-8"><a href="three-parameters.html#cb926-8"></a><span class="st">  </span><span class="kw">select</span>(subject, Control, Treated)</span>
<span id="cb926-9"><a href="three-parameters.html#cb926-9"></a></span>
<span id="cb926-10"><a href="three-parameters.html#cb926-10"></a>trains_RCM<span class="op">$</span>subject &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">"7"</span>, <span class="st">"6,041"</span>, <span class="st">"67"</span>, <span class="st">"40,080"</span>, <span class="st">"758"</span>, <span class="st">"32"</span>, <span class="st">"8,809"</span>)</span>
<span id="cb926-11"><a href="three-parameters.html#cb926-11"></a></span>
<span id="cb926-12"><a href="three-parameters.html#cb926-12"></a><span class="co">#Mathematical notation</span></span>
<span id="cb926-13"><a href="three-parameters.html#cb926-13"></a></span>
<span id="cb926-14"><a href="three-parameters.html#cb926-14"></a>trains_RCM <span class="op">%&gt;%</span></span>
<span id="cb926-15"><a href="three-parameters.html#cb926-15"></a><span class="st">  </span><span class="kw">gt</span>() <span class="op">%&gt;%</span></span>
<span id="cb926-16"><a href="three-parameters.html#cb926-16"></a><span class="st">  </span><span class="kw">cols_label</span>(<span class="dt">subject =</span> <span class="kw">md</span>(<span class="st">"**Subject**"</span>),</span>
<span id="cb926-17"><a href="three-parameters.html#cb926-17"></a>                <span class="dt">Control =</span> <span class="kw">md</span>(<span class="st">"**$$Y_c(u)$$**"</span>),</span>
<span id="cb926-18"><a href="three-parameters.html#cb926-18"></a>                <span class="dt">Treated =</span> <span class="kw">md</span>(<span class="st">"**$$Y_t(u)$$**"</span>)) <span class="op">%&gt;%</span></span>
<span id="cb926-19"><a href="three-parameters.html#cb926-19"></a><span class="st">  </span><span class="kw">tab_style</span>(<span class="kw">cell_borders</span>(<span class="dt">sides =</span> <span class="st">"right"</span>),</span>
<span id="cb926-20"><a href="three-parameters.html#cb926-20"></a>            <span class="dt">location =</span> <span class="kw">cells_body</span>(<span class="dt">columns =</span> <span class="kw">vars</span>(subject))) <span class="op">%&gt;%</span></span>
<span id="cb926-21"><a href="three-parameters.html#cb926-21"></a><span class="st">  </span><span class="kw">cols_align</span>(<span class="dt">align =</span> <span class="st">"center"</span>, <span class="dt">columns =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb926-22"><a href="three-parameters.html#cb926-22"></a><span class="st">  </span><span class="kw">tab_header</span>(<span class="dt">title =</span> <span class="st">"Ending Attitudes on Immigration of 7 Random Respondents"</span>)</span></code></pre></div>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#nlxmbmalkx .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#nlxmbmalkx .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nlxmbmalkx .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#nlxmbmalkx .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#nlxmbmalkx .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nlxmbmalkx .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nlxmbmalkx .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#nlxmbmalkx .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#nlxmbmalkx .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#nlxmbmalkx .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#nlxmbmalkx .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#nlxmbmalkx .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#nlxmbmalkx .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#nlxmbmalkx .gt_from_md > :first-child {
  margin-top: 0;
}

#nlxmbmalkx .gt_from_md > :last-child {
  margin-bottom: 0;
}

#nlxmbmalkx .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#nlxmbmalkx .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#nlxmbmalkx .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#nlxmbmalkx .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#nlxmbmalkx .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#nlxmbmalkx .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#nlxmbmalkx .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#nlxmbmalkx .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nlxmbmalkx .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nlxmbmalkx .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#nlxmbmalkx .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nlxmbmalkx .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#nlxmbmalkx .gt_left {
  text-align: left;
}

#nlxmbmalkx .gt_center {
  text-align: center;
}

#nlxmbmalkx .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#nlxmbmalkx .gt_font_normal {
  font-weight: normal;
}

#nlxmbmalkx .gt_font_bold {
  font-weight: bold;
}

#nlxmbmalkx .gt_font_italic {
  font-style: italic;
}

#nlxmbmalkx .gt_super {
  font-size: 65%;
}

#nlxmbmalkx .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="nlxmbmalkx" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="3" class="gt_heading gt_title gt_font_normal" style>Ending Attitudes on Immigration of 7 Random Respondents</th>
    </tr>
<tr>
<th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style></th>
    </tr>
</thead>
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Subject</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$Y_c(u)$$</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$Y_t(u)$$</strong></th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">7</td>
      <td class="gt_row gt_center">?</td>
      <td class="gt_row gt_center">11</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">6,041</td>
      <td class="gt_row gt_center">?</td>
      <td class="gt_row gt_center">10</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">67</td>
      <td class="gt_row gt_center">?</td>
      <td class="gt_row gt_center">5</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">40,080</td>
      <td class="gt_row gt_center">?</td>
      <td class="gt_row gt_center">11</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">758</td>
      <td class="gt_row gt_center">5</td>
      <td class="gt_row gt_center">?</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">32</td>
      <td class="gt_row gt_center">?</td>
      <td class="gt_row gt_center">13</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">8,809</td>
      <td class="gt_row gt_center">13</td>
      <td class="gt_row gt_center">?</td>
    </tr>
</tbody>
</table></div>
<p>Recall that the Rubin Causal Model centers on filling in the unknowns, which are indicated by the “?”s in the table. There’s one way we could fill in the missing values — we could use our approximations we generated with our <code>lm()</code> model: that is, for each unknown Treated value, we use 10, and for each unknown Control value, we use 8.45.</p>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#lzqxyjoorb .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#lzqxyjoorb .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lzqxyjoorb .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#lzqxyjoorb .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#lzqxyjoorb .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lzqxyjoorb .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lzqxyjoorb .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#lzqxyjoorb .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#lzqxyjoorb .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#lzqxyjoorb .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#lzqxyjoorb .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#lzqxyjoorb .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#lzqxyjoorb .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#lzqxyjoorb .gt_from_md > :first-child {
  margin-top: 0;
}

#lzqxyjoorb .gt_from_md > :last-child {
  margin-bottom: 0;
}

#lzqxyjoorb .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#lzqxyjoorb .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#lzqxyjoorb .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#lzqxyjoorb .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#lzqxyjoorb .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#lzqxyjoorb .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#lzqxyjoorb .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#lzqxyjoorb .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lzqxyjoorb .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lzqxyjoorb .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#lzqxyjoorb .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lzqxyjoorb .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#lzqxyjoorb .gt_left {
  text-align: left;
}

#lzqxyjoorb .gt_center {
  text-align: center;
}

#lzqxyjoorb .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#lzqxyjoorb .gt_font_normal {
  font-weight: normal;
}

#lzqxyjoorb .gt_font_bold {
  font-weight: bold;
}

#lzqxyjoorb .gt_font_italic {
  font-style: italic;
}

#lzqxyjoorb .gt_super {
  font-size: 65%;
}

#lzqxyjoorb .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="lzqxyjoorb" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="3" class="gt_heading gt_title gt_font_normal" style>Ending Attitudes on Immigration of 7 Random Respondents</th>
    </tr>
<tr>
<th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style></th>
    </tr>
</thead>
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Subject</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$Y_c(u)$$</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$Y_t(u)$$</strong></th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">7</td>
      <td class="gt_row gt_center">8.45</td>
      <td class="gt_row gt_center">11</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">6,041</td>
      <td class="gt_row gt_center">8.45</td>
      <td class="gt_row gt_center">10</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">67</td>
      <td class="gt_row gt_center">8.45</td>
      <td class="gt_row gt_center">5</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">40,080</td>
      <td class="gt_row gt_center">8.45</td>
      <td class="gt_row gt_center">11</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">758</td>
      <td class="gt_row gt_center">5</td>
      <td class="gt_row gt_center">10</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">32</td>
      <td class="gt_row gt_center">8.45</td>
      <td class="gt_row gt_center">13</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">8,809</td>
      <td class="gt_row gt_center">13</td>
      <td class="gt_row gt_center">10</td>
    </tr>
</tbody>
</table></div>
<p>This table looks a bit funky: take a look at subject 67. According to this model, subject 67’s attitude under control would be HIGHER than his/her attitude under treatment, which corresponds to a negative treatment effect. This would mean that he/she would become more LIBERAL after undergoing treatment, which flies in the face of the ATE we calculated earlier. Another example of this can be seen with subject 32, whose predicted <code>att_end</code> under treatment is lower than his/her <code>att_end</code> under control (also signifying a shift towards liberal attitudes regarding immigration).</p>
<p>Clearly, using the same control and treatment values to fill in the unknowns doesn’t capture the entire picture as it does with a predictive model. While using <code>lm()</code> to fill in the <code>att_end</code> unknowns towards the center of the distribution, it makes less sense for values towards the outskirts of the dataset. So, how can we predict outcomes in a way that equally addresses data towards the center of the distribution, and data that isn’t?</p>
<p>One such way is by attaching the ATE, which we previously calculated to be -1.55, in the appropriate direction to fill in the unknowns:</p>
<pre><code>## # A tibble: 2 x 4
##   term             estimate conf.low conf.high
##   &lt;chr&gt;               &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)          8.45    7.77       9.14
## 2 treatmentTreated     1.55    0.514      2.58</code></pre>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#wxpzbvdpvn .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#wxpzbvdpvn .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wxpzbvdpvn .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#wxpzbvdpvn .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#wxpzbvdpvn .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wxpzbvdpvn .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wxpzbvdpvn .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#wxpzbvdpvn .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#wxpzbvdpvn .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#wxpzbvdpvn .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#wxpzbvdpvn .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#wxpzbvdpvn .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#wxpzbvdpvn .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#wxpzbvdpvn .gt_from_md > :first-child {
  margin-top: 0;
}

#wxpzbvdpvn .gt_from_md > :last-child {
  margin-bottom: 0;
}

#wxpzbvdpvn .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#wxpzbvdpvn .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#wxpzbvdpvn .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wxpzbvdpvn .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#wxpzbvdpvn .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wxpzbvdpvn .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#wxpzbvdpvn .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#wxpzbvdpvn .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wxpzbvdpvn .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wxpzbvdpvn .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#wxpzbvdpvn .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wxpzbvdpvn .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#wxpzbvdpvn .gt_left {
  text-align: left;
}

#wxpzbvdpvn .gt_center {
  text-align: center;
}

#wxpzbvdpvn .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#wxpzbvdpvn .gt_font_normal {
  font-weight: normal;
}

#wxpzbvdpvn .gt_font_bold {
  font-weight: bold;
}

#wxpzbvdpvn .gt_font_italic {
  font-style: italic;
}

#wxpzbvdpvn .gt_super {
  font-size: 65%;
}

#wxpzbvdpvn .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="wxpzbvdpvn" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="3" class="gt_heading gt_title gt_font_normal" style>Ending Attitudes on Immigration of 7 Random Respondents</th>
    </tr>
<tr>
<th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style></th>
    </tr>
</thead>
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Subject</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$Y_c(u)$$</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$Y_t(u)$$</strong></th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">7</td>
      <td class="gt_row gt_center">9.45</td>
      <td class="gt_row gt_center">11</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">6,041</td>
      <td class="gt_row gt_center">8.45</td>
      <td class="gt_row gt_center">10</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">67</td>
      <td class="gt_row gt_center">3.45</td>
      <td class="gt_row gt_center">5</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">40,080</td>
      <td class="gt_row gt_center">9.45</td>
      <td class="gt_row gt_center">11</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">758</td>
      <td class="gt_row gt_center">5</td>
      <td class="gt_row gt_center">6.55</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">32</td>
      <td class="gt_row gt_center">11.45</td>
      <td class="gt_row gt_center">13</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">8,809</td>
      <td class="gt_row gt_center">13</td>
      <td class="gt_row gt_center">14.55</td>
    </tr>
</tbody>
</table></div>
<p>The usage of this table shows how a causal model is used differently than a predictive model. Unlike before, it wasn’t enough to fill in our unknowns with the parameter estimates. This is because we aren’t merely predicting their att_end, a variable that, unlike age, could be changed by exposure to a treatment variable. By using the ATE, we were able to make a more informed prediction on any individual’s att_end had they been placed in the other group.</p>
</div>
<div id="parameter-uncertainty" class="section level3">
<h3>
<span class="header-section-number">8.3.6</span> Parameter Uncertainty</h3>
<p>Here, we see that the average treatment effect is -1.55; this is the average change in att_end caused by treatment (if this statistic looks unfamiliar, refer back to chapter 3 for a refresher on ATE). But how confident are we in this ATE? We can use <code>lm()</code> again to generate confidence intervals for our parameters and for this value:</p>
<div class="sourceCode" id="cb928"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb928-1"><a href="three-parameters.html#cb928-1"></a><span class="co">#This is necessary so we can see the offset as caused by treatmentTreated, not treatmentControl.</span></span>
<span id="cb928-2"><a href="three-parameters.html#cb928-2"></a></span>
<span id="cb928-3"><a href="three-parameters.html#cb928-3"></a>trains<span class="op">$</span>treatment &lt;-<span class="kw">fct_relevel</span>(trains<span class="op">$</span>treatment, <span class="st">"Control"</span>, <span class="st">"Treated"</span>)</span>
<span id="cb928-4"><a href="three-parameters.html#cb928-4"></a></span>
<span id="cb928-5"><a href="three-parameters.html#cb928-5"></a><span class="kw">lm</span>(<span class="dt">data =</span> trains, att_end <span class="op">~</span><span class="st"> </span>treatment <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb928-6"><a href="three-parameters.html#cb928-6"></a><span class="st">  </span><span class="kw">tidy</span>(<span class="dt">conf.int =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb928-7"><a href="three-parameters.html#cb928-7"></a><span class="st">  </span><span class="kw">select</span>(term, estimate, conf.low, conf.high)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   term             estimate conf.low conf.high
##   &lt;chr&gt;               &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 treatmentControl     8.45     7.77      9.14
## 2 treatmentTreated    10.       9.23     10.8</code></pre>
<div class="sourceCode" id="cb930"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb930-1"><a href="three-parameters.html#cb930-1"></a><span class="kw">summary</span>(<span class="kw">lm</span>(<span class="dt">data =</span> trains, att_end <span class="op">~</span><span class="st"> </span>treatment <span class="op">-</span><span class="st"> </span><span class="dv">1</span>))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = att_end ~ treatment - 1, data = trains)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -6.00  -2.00   0.00   2.00   6.55 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## treatmentControl    8.453      0.347    24.4   &lt;2e-16 ***
## treatmentTreated   10.000      0.389    25.7   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.8 on 113 degrees of freedom
## Multiple R-squared:  0.917,	Adjusted R-squared:  0.916 
## F-statistic:  627 on 2 and 113 DF,  p-value: &lt;2e-16</code></pre>
<!-- MB: Is this true  -->
<p>Our measure of confidence for the ATE is known as the residual standard error, which in this case is 2.78. The residual standard error show our confidence in the average treatment effect of the <code>trains</code> dataset being representative of the true average treatment effect on Boston commuters.</p>
</div>
<div id="uncertainties" class="section level3">
<h3>
<span class="header-section-number">8.3.7</span> Uncertainties</h3>

</div>
</div>
</div></body></html>

<p style="text-align: center;">
<a href="two-parameters.html"><button class="btn btn-default">Previous</button></a>
<a href="n-parameters.html"><button class="btn btn-default">Next</button></a>
</p>
<p class="build-date">Page built: 
2020-10-13
</p>
</div>
</div>



</body>
</html>
